### ISSUE TITLE
Greeted with error message after fresh installation on CentOS7

### ISSUE THREAD

**Issue by hamzamohdzubair** [LunarVim/LunarVim#4303] opened 2023-07-19 10:00 UTC
### Problem description

I have done a fresh installation of lvim on a centos7 server. And every time I start lvim and open the first file, i am greeted with error given in screenshot. Before i open any file, the error does not come and i can browse files in nvim tree and it is smooth. After i open a file and after the error is displayed, lvim starts to lag. **Moving the cursor has 1-sec delay.**

#### 1. pre-requisite installation
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-venv
sudo apt-get install python3-pip
rustup update
```
#### 2. node installation
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install node
```

#### 3. nvim installation:
```
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
mv nvim.appimage .local/bin/nvim
```

#### 4. removing previous lvim files
```
rm -rf ~/.config/lvim
rm -rf ~/.cache/lvim
rm -rf ~/.local/share/lvim
rm -rf ~/.local/share/lunarvim
```

#### 5. pip version
```
❯ pip3 --version
pip 21.3.1
```

#### 6. node version
```
❯ nvm -v
0.39.3
❯ node -v
v16.20.1
❯ npm -v
8.19.4
```
#### 7. rust version
```
❯ cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
❯ rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
❯ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)`
```
#### 8. nvim version:
```
❯ nvim -v
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
#### 9. Lunarvim Installation:
```
LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
```

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

NVIM v0.9.1

### Terminal name

Tilde

### Operating system/version

CentOS Linux 7 (Core)

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/13695228/6b427f1d-c1b6-4d7b-a96a-785a9bbfe4cd)

**Comment by LostNeophyte** [comment] 2023-07-19 13:34
interesting, looks like a duplicate of https://github.com/LunarVim/LunarVim/issues/4181
but you have nvim 0.9.1, where I can't reproduce the issue, try running :LvimUpdate and :Lazy sync

**Comment by hamzamohdzubair** [comment] 2023-07-19 13:45
> interesting, looks like a duplicate of #4181 but you have nvim 0.9.1, where I can't reproduce the issue, try running ~:LvimUpdate and~ :Lazy sync
> 
> P.S. thanks for the detailed info

I tried `:Lazy sync` before opening any file. no difference.

**Comment by LostNeophyte** [comment] 2023-07-19 13:49
what's the `commit` of nvim-treesitter in `:Lazy` (press enter to show details)

**Comment by hamzamohdzubair** [comment] 2023-07-19 13:54
`commit: 2ce3c90`
![image](https://github.com/LunarVim/LunarVim/assets/13695228/35a8fa31-4a6b-4486-b744-376497ef87b7)

**Comment by LostNeophyte** [comment] 2023-07-19 13:56
looks good, what's the output of `:checkhealth nvim-treesitter`, do you have any extra treesitter plugins?

**Comment by hamzamohdzubair** [comment] 2023-07-19 13:58
> looks good, what's the output of `:checkhealth nvim-treesitter`, do you have any extra treesitter plugins?

I am sorry for getting away with screenshots, i haven't figured out copy-paste in my work setup.

![image](https://github.com/LunarVim/LunarVim/assets/13695228/6a324021-8114-4fdd-8203-a460925fd8d0)

**Comment by LostNeophyte** [comment] 2023-07-19 14:05
> I am sorry for getting away with screenshots, i haven't figured out copy-paste in my work setup.

np, in most cases it's easier to read screenshots, I only prefer text for errors. you can probably hold shift while selecting with the mouse and ctrl+shift+c to copy while bypassing nvim

I have only one idea left, check `:lua =vim.version()`.
if it returns this then idk what to do
```
{                                                                                                                                                                                                                                               
  api_compatible = 0,                                                                                                                                                                                                                           
  api_level = 11,                                                                                                                                                                                                                               
  api_prerelease = false,                                                                                                                                                                                                                       
  major = 0,                                                                                                                                                                                                                                    
  minor = 9,                                                                                                                                                                                                                                    
  patch = 1,                                                                                                                                                                                                                                    
  prerelease = false                                                                                                                                                                                                                            
}   
```

**Comment by hamzamohdzubair** [comment] 2023-07-19 14:09
> I have only one idea left, check `:lua =vim.version()`.

![image](https://github.com/LunarVim/LunarVim/assets/13695228/8cf40a31-13f1-4cc0-a531-077bdb3c7c5c)

**Comment by LostNeophyte** [comment] 2023-07-19 14:15
here we go, looks like you have multiple nvims installed. the nvim version that your installation is using is 0.10.0-dev, you can probably check which one lvim is using with `:!which nvim`, make sure that it's the right one by doing `:!nvim --version`, if i'm correct if will be 0.10.0 dev

**Comment by hamzamohdzubair** [comment] 2023-07-19 14:17
my main page says `neovim-0.9` but

![image](https://github.com/LunarVim/LunarVim/assets/13695228/db227914-1f00-4d15-bdcd-90cc6a75bcbf)

**Comment by LostNeophyte** [comment] 2023-07-19 14:20
that full line is the lunarvim version, we include the required neovim version in the branch name after the slash, and after the dash is the commit of the lvim version

**Comment by hamzamohdzubair** [comment] 2023-07-19 14:20
> here we go, looks like you have multiple nvims installed. the nvim version that your installation is using is 0.10.0-dev, you can probably check which one lvim is using with `:!which nvim`, make sure that it's the right one by doing `:!nvim --version`, if i'm correct if will be 0.10.0 dev

yes you are right. There is a system-wide neovim that is v0.10 located at: `/usr/local/bin/nvim`

how do i not use it.

i had added this in my `.bashrc`:
`alias nvim=~/.local/bin/nvim` (this is 0.9.1)

so this is not enough?

**Closed** 2023-07-19 14:25 UTC
Labels: bug

**Comment by hamzamohdzubair** [comment] 2023-07-19 14:37
> make sure ~/.local/bin is earlier in path than /usr/local/bin, so
> 
> use `export PATH=~/local/bin:$PATH` instead of `export PATH=$PATH:~/local/bin`

Just for information. On doing the above, not only the error is gone, but lunarvim is not laggy as well. Speed restored.
Faith restored 😄.
