### ISSUE TITLE
Please provide linux appimage of lunarVim!!

### ISSUE THREAD

**Issue by meicale** [LunarVim/LunarVim#3575] opened 2022-12-06 03:26 UTC
### Feature Description

I think lunarVim is  an excellent distribution. It provides install script which makes it not that difficult to install and take advantage of. But  it may fail or have a different experience due to network reason, etc. I suggest that we can do all the installation into a AppImage just like neovim provides. 

### Describe the alternatives you have considered

An other option is  dockerfile or docker image which has all those dependecies and plugins installed. Thx!

### Support information

ref:
https://github.com/AppImage/appimagekit
https://appimage.org/
https://github.com/neovim/neovim
https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package

**Comment by LostNeophyte** [comment] 2022-12-06 06:59
the neovim appimage is problematic iirc, [we do have a dockerfile](https://github.com/LunarVim/LunarVim/blob/master/utils/docker/Dockerfile.remote), it works but then the builtin terminal and clipboard are kinda useless

**Comment by vtta** [comment] 2022-12-08 08:16
have wanted this for ages! 
Appimage does not use any container technology, so it does not have the terminal/clipboard problem.
I have been using appimage version of neovim, not so bad for me currently

**Comment by LostNeophyte** [comment] 2022-12-08 09:05
I'm not sure if it's possible though, from what I know appimages are immutable, so installing user plugins would be impossible unless we put them outside of the appimage, but then the appimage would need to install them on the user's filesystem on the first run and that kinda ruins the whole point of it right? (it would be just a bundle of neovim with a shorter version of the lunarvim install script, which kinda makes no sense)

**Comment by vtta** [comment] 2022-12-08 09:49
> installing user plugins would be impossible unless we put them outside of the appimage, but then the appimage would need to install them on the user's filesystem on the first run

After playing around a little bit, I think one possible approach is doing a separation between `lvim`'s bundled package and user's defined packages.
We can bundle the `LUNARVIM_RUNTIME_DIR`/`LUNARVIM_BASE_DIR` inside appimage and leave `LUNARVIM_CONFIG_DIR`/`LUNARVIM_CACHE_DIR` to be user's home directory. If users opt to modify configuration its plugin will be installed inside `LUNARVIM_CONFIG_DIR` and leave appimage not changed.

We can also let people give their `config.lua` and compile an appimage at installation. Because I think most of people will not change the configuration any more once they settle down on a  comfortable one. In this case, people can also enjoy the benefit of portability as well as their tailored environment when deploy the generated `lvim.appimage` on different machines.

But of course both of the two points need significant restructure for now.

**Comment by LostNeophyte** [comment] 2022-12-08 09:56
> After playing around a little bit, I think one possible approach is doing a separation between lvim's bundled package and user's defined packages. [...] If users opt to modify configuration, their plugins will be installed inside LUNARVIM_CONFIG_DIR and leave the provided appimage not changed

I think it's impossible, packer only supports one package directory so we'd need to hande the core plugins ourselves which is not worth it

**Comment by meicale** [comment] 2022-12-11 01:09
> the neovim appimage is problematic iirc (or was it the flatpak?), [we do have a dockerfile](https://github.com/LunarVim/LunarVim/blob/master/utils/docker/Dockerfile.remote), it works but then the builtin terminal and clipboard are kinda useless

I use the appImage of neovim on kinds of machine. It works fine for me and It is just so easy to running up.

**Comment by meicale** [comment] 2022-12-11 01:14
> > have wanted this for ages! Appimage does not use any container technology, so it does not have the terminal/clipboard problem. I have been using appimage version of neovim, not so bad for me currently
> 
> if a couple more people will use this, I'll try to do it

I think no one refuse easier way to use LunarVim if the default config satisfies them.

**Comment by meicale** [comment] 2022-12-11 01:16
> > have wanted this for ages! Appimage does not use any container technology, so it does not have the terminal/clipboard problem. I have been using appimage version of neovim, not so bad for me currently
> 
> if a couple more people will use this, I'll try to do it

I think no one refuse easier way to use LunarVim if the default config satisfies them.

**Comment by LostNeophyte** [comment] 2022-12-11 15:40
okay so no promises, it might be abandoned, but I have something

can you check if [this](https://mega.nz/file/eeoFERpA#g_QxruVufYUDYU66jBN27vrcEKzlkwrOQDRRGWQGUQQ) appimage works? if you don't have lunarvim already installed on your machine, you'll need to run `:PackerSync` on the first run. In the appimage everything (except updating lvim core) should work, this includes adding user plugins, removing core plugins and updating plugins

**Comment by LostNeophyte** [comment] 2022-12-13 07:46
duplicate of #1511

**Closed by LostNeophyte** 2022-12-13 07:46 UTC
Labels: enhancement

**Comment by meicale** [comment] 2022-12-18 01:17
I wonder that lvim use different config files and plugin directories, so can we install lvim in a docker container and make it a volume which can be mounted by another container? This may be helpful if we use it aside by dev-container like what happens in VSCode.
