### ISSUE TITLE
Error detected while processing .local/share/lunarvim/lvim/init.lua:

### ISSUE THREAD

**Issue by jjmartres** [LunarVim/LunarVim#2166] opened 2022-01-11 10:02 UTC
### Problem description

- run `bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh` 
- install lvim again `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
- run `lvim`

### LunarVim version

1.0.0

### Neovim version (>= 0.6)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.1

### Relevant log output

```shell
Error detected while processing /Users/jeanjacques.martres@fintecture.com/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:180: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        vim/_meta.lua:180: in function 'set_scoped_option'
        vim/_meta.lua:682: in function '_set'
        vim/_meta.lua:724: in function '__newindex'
        .../.local/share/lunarvim/lvim/lua/lvim/config/settings.lua:58: in function 'load_default_options'
        .../.local/share/lunarvim/lvim/lua/lvim/config/settings.lua:75: in function 'load_options'
        ....com/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:35: in function 'init'
        ...re.com/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:104: in function 'init'
        ...rtres@fintecture.com/.local/share/lunarvim/lvim/init.lua:8: in main chunk
Press ENTER or type command to continue
```
```


### Screenshots

_No response_

**Comment by kylo252** [comment] 2022-01-12 09:07
Looks like a problem with your neovim installation, probably an out-ot-sync runtime files. Please try removing neovim completely and then re-installing it again.

**Comment by jjmartres** [comment] 2022-01-12 10:18
@kylo252 I've try the following:

- uninstall LunarVim
- uninstall NeoVim
- Install Neovim using brew
- Install LunarVim

But I got the same error.

**Comment by kylo252** [comment] 2022-01-12 11:00
Please try these steps
1. make sure it's not the cache_dir that's causing the issue 
```vim
:lua print(vim.loop.fs_stat(get_cache_dir()).type)
:! ls $LUNARVIM_CACHE_DIR
```
2. comment out `undodir`, `spellfile`, `shadafile`, from https://github.com/LunarVim/LunarVim/blob/d0840511d81abc08502d3f18da89d03025dcf373/lua/lvim/config/settings.lua
3. if it still doesn't work, then comment out this section https://github.com/LunarVim/LunarVim/blob/d0840511d81abc08502d3f18da89d03025dcf373/lua/lvim/config/settings.lua#L57-L59
and set some settings manually

**Comment by jjmartres** [comment] 2022-01-12 11:13
@kylo252 comment out `undodir`, `spellfile` and `shadafile` has solve my issue

**Comment by kylo252** [comment] 2022-01-12 11:42
> @kylo252 comment out `undodir`, `spellfile` and `shadafile` has solve my issue

I'm suspecting that it's neovim bug related to `spellfile`, probably even related to https://github.com/LunarVim/LunarVim/issues/2045

I want to verify it, so please try these, to see if any of these is broken

```bash
nvim -u NONE --headless -c "lua vim.opt.spellfile=vim.fn.stdpath('config') .. '/spell/en.utf-8.add'" -c 'echo &spellfile' -c 'quitall'
nvim -u NONE --headless -c "lua vim.opt.spellfile=\"$HOME/.config/nvim/spell/en.utf-8.add\"" -c 'echo &spellfile'  -c 'quitall'
nvim -u NONE --headless -c "set spellfile=\"$HOME/.config/nvim/spell/en.utf-8.add\"" -c 'echo &spellfile'  -c 'quitall'
```

**Comment by free-150** [comment] 2022-01-12 12:46
I have the same problem

**Comment by jjmartres** [comment] 2022-01-12 13:00
@kylo252 

here is the result:

```
 ➜ ~ nvim -u NONE --headless -c "lua vim.opt.spellfile=vim.fn.stdpath('config') .. '/spell/en.utf-8.add'" -c 'echo &spellfile' -c 'quitall'
Error detected while processing command line:
E5108: Error executing lua vim/_meta.lua:180: E474: Invalid argument
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	vim/_meta.lua:180: in function 'set_scoped_option'
	vim/_meta.lua:682: in function '_set'
	vim/_meta.lua:724: in function '__newindex'
	[string ":lua"]:1: in main chunk

➜ ~ nvim -u NONE --headless -c "lua vim.opt.spellfile=\"$HOME/.config/nvim/spell/en.utf-8.add\"" -c 'echo &spellfile'  -c 'quitall'
Error detected while processing command line:
E5108: Error executing lua vim/_meta.lua:180: E474: Invalid argument
stack traceback:
	[C]: in function 'nvim_buf_set_option'
	vim/_meta.lua:180: in function 'set_scoped_option'
	vim/_meta.lua:682: in function '_set'
	vim/_meta.lua:724: in function '__newindex'
	[string ":lua"]:1: in main chunk

➜ ~  nvim -u NONE --headless -c "set spellfile=\"$HOME/.config/nvim/spell/en.utf-8.add\"" -c 'echo &spellfile'  -c 'quitall'
```

**Comment by kylo252** [comment] 2022-01-12 14:09
> here is the result:

@jjmartres, please open a ticket at https://github.com/neovim/neovim/issues with this minimal reproduce that you just shared. You can probably title it: 
> E474: Invalid argument when setting `vim.opt.spellfile`

**Comment by kylo252** [comment] 2022-01-12 14:12
> I have the same problem

@free-150, are you on latest? Please delete `~/.config/lvim/plugin/packer_compiled.lua` and then run `:PackerSync`

**Comment by jjmartres** [comment] 2022-01-12 16:41
@kylo252 case opened: https://github.com/neovim/neovim/issues/17059

**Comment by halas** [comment] 2022-01-12 17:22
I had the same issue on macos with nvim 0.6 and not sure now which version of Lunar, but uninstalling lunarvim, updating neovim to 0.6.1 and installing lunarvim again solved it.

**Comment by jjmartres** [comment] 2022-01-17 08:48
@kylo252 I got the following answer on the case opened on neovim side:

```
if you try to pass a string that is not an *.add file, you'll get that error (which, granted, might be made more explicit).
```

Not sure to understand what is going wrong

**Comment by vhscom** [comment] 2022-02-22 06:33
Resolved on macOS after uninstalling lunarvim, brew reinstalling neovim, installing lunarvim again, starting lunarvim, then running `:LvimCacheReset` followed by `:LvimUpdate` followed by `:LvimReload`.

**Comment by abzcoding** [comment] 2022-05-03 02:19
this should be fixed

**Comment by MyraBaba** [comment] 2022-05-08 20:19
really blocking issue on the Mac Os x catalina.

Almost we are leaving lunarvim..

:(

**Closed** 2022-05-21 14:48 UTC
Labels: bug, packaging
