### ISSUE TITLE
[Feature]: Use Telescope's git_files instead of find_files by default

### ISSUE THREAD

**Issue by LandonSchropp** [LunarVim/LunarVim#2088] opened 2021-12-15 23:44 UTC
### Feature motivation

Using Telescope's `find_files` keybinding can be a bit of a pain. By default, this doesn't display hidden files in LunarVim, and if you set `lvim.builtin.telescope.pickers = { find_files = { hidden = true } }`, then the finder displays all of the files in the `.git` directory.

### Describe the expected solution

I just discovered that Telescope has a built-in `git_files` function. This works exactly like `find_files`, except it displays all files in the current repo not ignored by the `.gitignore` file. 

The one downside to this picker is that it produces an error when not in a git directory. I'd propose that LunarVim add a function that displays `git_files` when in a Git repo, and falls back to `find_files` when not.

### Describe the alternatives you've considered

I've already set my local config to use this, but this feels like a sane default most developers would want.

**Comment by LandonSchropp** [comment] 2021-12-16 00:17
If you guys are up for it, I'm happy to make this change. The only thing I'm not sure about is how to detect if the working directory is contained in a Git repo. Is LunarVim already doing this somewhere else in the source code?

**Comment by mandaputtra** [comment] 2021-12-16 01:47
This is usefull! +1 on this feature.

**Comment by kylo252** [comment] 2021-12-16 07:44
This should not be necessary as long as you have `fd` installed. I literally made #1702 for this exact reason, so you can override the default find command to whatever you want anyway. Also, `fd` actually respects `.gitignore` by default.

Maybe something has changed that broke the integration, but that should be addressed directly if that's the case.

**Comment by LandonSchropp** [comment] 2021-12-16 19:48
@kylo252 I didn't realize that `fd` was the preferred alternative for handling this. I'm happy to use that if that's the case.

I'm not sure if the command is working for me as intended right now. If I enable the hidden files settings from above, I see all of the files in the `.git` directory.

<img width="969" alt="Screen Shot 2021-12-16 at 1 46 01 PM" src="https://user-images.githubusercontent.com/361591/146438440-38d11fa0-30be-476c-9dde-864c45062e76.png">

This seems to track with the behavior that I see when running `fd --type=file --hidden` locally—all of the files in `.git` are displayed.

Also, I noticed the `--smart-case` option was included in the PR you provided. However, I try to include that flag on locally, I get this error:

<img width="1010" alt="Screen Shot 2021-12-16 at 1 48 29 PM" src="https://user-images.githubusercontent.com/361591/146438710-f6f5301d-6933-4cd6-bd4d-957893e5e0b4.png">

**Comment by kylo252** [comment] 2021-12-17 08:48
The `.git/` folder is indeed "hidden" but it's not git-ignored, meaning that `fd` _tecnically_ works as designed.


I've always overridden that behavior locally, since I don't like it

- `fd`: https://github.com/kylo252/dotfiles/blob/d57104174d6182760ecc595b273d2a0de10bfd1e/.config/fd/ignore
- `ripgrep`: https://github.com/kylo252/dotfiles/blob/d57104174d6182760ecc595b273d2a0de10bfd1e/.config/ripgrep/ripgreprc

Since I've had this discussion a few times already about `fd` and `ripgrep`, maybe it's time to actually address it. The way I see it, there are two available options:

#### Alternative (1)
Add a new `--glob` flag for both `fd` and `riprep` with common "sane" values. 
- Pros: easy to add.
- Cons: problem with that is that I'm not confident these flags will be propagated to all the telescope pickers that re-use `fd` or `rg`.

#### Alternative (2)
Let the installer create default rc files if they don't exist already.
- Pros: consistent search behavior everywhere.
- Cons: a bit harder to implement, since we need to add a new hook. On the other hand, we shouldn't overwrite the default values, so we're hoping these existing rc files contain "sane" values, maybe there's some flag to dump the current config(?)

**Comment by kylo252** [comment] 2021-12-17 08:49
cc: @abzcoding, @ChristianChiarulli

**Comment by abzcoding** [comment] 2021-12-17 17:33
> cc: @abzcoding, @ChristianChiarulli

i mean i kind of like the proposed PR by @LandonSchropp , so i'd be happy if that gets merged

**Comment by kylo252** [comment] 2021-12-18 13:18
> i mean i kind of like the proposed PR by @LandonSchropp , so i'd be happy if that gets merged

Sure. but that doesn't really solve the issue with `fd` 😕

**Comment by abzcoding** [comment] 2021-12-18 13:21
> > i mean i kind of like the proposed PR by @LandonSchropp , so i'd be happy if that gets merged
> 
> Sure. but that doesn't really solve the issue with `fd` 😕

sadly yes, but i think we should let users handle that one themselves like what you did in your dotfiles

**Closed** 2021-12-23 08:56 UTC
Labels: enhancement
