### ISSUE TITLE
[Bug]: install fails due to unrecognized rsync flag

### ISSUE THREAD

**Issue by nzlov** [LunarVim/LunarVim#1385] opened 2021-08-24 00:35 UTC
### Problem description

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

### LunarVim version

rolling

### Neovim version (>= 0.5)

NVIM v0.5.0

### Screenshots

![image](https://user-images.githubusercontent.com/2859981/130536962-3422b609-e698-4423-9982-3df98467825b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by mandaputtra** [comment] 2021-08-24 01:18
There are also installation error when using `rolling` branch.

![Screenshot from 2021-08-24 08-17-43](https://user-images.githubusercontent.com/23342943/130540087-cdaf7fd9-993d-4640-b793-8d485d9b63cd.png)

![Screenshot from 2021-08-24 08-18-03](https://user-images.githubusercontent.com/23342943/130540105-82822a97-5e0d-4b83-8fc5-ebf4978f189e.png)

**Comment by abzcoding** [comment] 2021-08-24 06:26
cc: @kylo252

**Comment by kylo252** [comment] 2021-08-24 07:16
The first problem should be fixed with f6c706ac0c346491cc79bdea46a52ee7a8694e0d
---
@mandaputtra, what platform are you on?

**Comment by mandaputtra** [comment] 2021-08-24 07:19
It just quit if i run it with `--overwrite` flag

**Comment by kylo252** [comment] 2021-08-24 07:33
> It just quit if i run it with `--overwrite` flag

Are you on Linux or macOS? I have a feeling your shell does not like `read`. You can also skip the `--overwrite` flag for now.

**Comment by mandaputtra** [comment] 2021-08-24 07:36
I use Linux using zsh. Okay then no problem. How do you ussay debug the
install script?

**Comment by kylo252** [comment] 2021-08-24 07:43
I think I found out what the problem is, it's related to the stdin pipe.

![image](https://user-images.githubusercontent.com/59826753/130577079-6a0a9f1d-b503-479a-968a-109df03beec2.png)

Solution: stop piping into bash 😄

**Comment by mandaputtra** [comment] 2021-08-24 11:02
Yup works out! I think the issue is closed now

**Closed** 2021-08-24 13:19 UTC
Labels: bug
