### ISSUE TITLE
Error - attempt to index local 'uri'

### ISSUE THREAD

**Issue by carloseguevara** [LunarVim/LunarVim#1516] opened 2021-09-09 15:57 UTC
Today, I update my local version of lunarvim and get this error any time that I change anything in someone file: 
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/uri.lua:116: attempt to index local 'uri' (a nil value)

I dont understand what is the trouble, or if I do something wrong updating, but twice a week, I update my local version.

**Comment by abzcoding** [comment] 2021-09-09 16:10
duplicate of https://github.com/LunarVim/LunarVim/issues/1499
plz downgrade to `neovim 0.5 release`

**Closed by abzcoding** 2021-09-09 16:10 UTC
