### ISSUE TITLE
treesitter/highlighter: error executing lua error

### ISSUE THREAD

**Issue by woshichuanqilz** [LunarVim/LunarVim#3465] opened 2022-11-13 02:03 UTC
### Problem description

![image](https://user-images.githubusercontent.com/11295355/201501921-2d93696c-3c66-417c-a106-09b7a58fe658.png)

### LunarVim version

release-1.2/neovim-0.8-c1d4f5e

### Neovim version (>= 0.8.0)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

OS: Ubuntu 22.04 jammy

### support info

```console
Use [q] or [Esc] to quit the window                            │
│                                                                       │
│        Language client log: /home/lizhe/.local/state/nvim/lsp.        │
│                                 log                                   │
│        Detected filetype:   alpha                                     │
│                                                                       │
│        0 client(s) attached to this buffer:                           │
│                                                                       │
│        Configured servers list: 
```

```console
  │Buffer info                                             │      │
│       │* filetype:                alpha                        │      │
│       │* bufnr:                   1                            │      │
│       │* treesitter status:       inactive                     │      │
│       │                                                        │      │
│       │Active client(s)                                        │      │
│       │                                                        │      │
│       │Automatic LSP info                                      │      │
│       │* Skipped servers: [angularls, ansiblels, csharp_ls, css│      │
│       │                                                        │      │
│       │Formatters info                                         │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│       │Linters info                                            │      │
│       │* Active:                                               │      │
│       │* Supported: []                                         │      │
│       │                                                        │      │
│~      │Code actions info                                       │      │
│~      │* Active:  
```

**Comment by LostNeophyte** [comment] 2022-11-13 06:44
Duplicate of https://github.com/LunarVim/LunarVim/issues/3460

**Closed by LostNeophyte** 2022-11-13 06:44 UTC
Labels: bug

**Comment by woshichuanqilz** [comment] 2022-11-13 09:00
> Duplicate of #3460

Thank you, and 
How to check the whole error message ? Some message go out of the screen

**Comment by LostNeophyte** [comment] 2022-11-13 09:13
> > Duplicate of #3460
> 
> Thank you, and How to check the whole error message ? Some message go out of the screen

with mosh errors you can do `:messages`, but here I'm not sure if it's possible
