### ISSUE TITLE
Loading issue on fresh installation

### ISSUE THREAD

**Issue by chan-dev** [LunarVim/LunarVim#4302] opened 2023-07-19 06:54 UTC
### Problem description

This issue occurs on a newly installed one.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.0)

v0.10.0-dev

### Terminal name

xfce4-terminal

### Operating system/version

Ubuntu  22.04.2 LTS

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/46891115/43a27033-d72e-4f6b-94f0-e6a83f2bc4a8)

**Comment by LostNeophyte** [comment] 2023-07-19 07:29
duplicate of https://github.com/LunarVim/LunarVim/issues/4181

**Closed by LostNeophyte** 2023-07-19 07:29 UTC
Labels: bug
