### ISSUE TITLE
[Feature] Lvim Nix package

### ISSUE THREAD

**Issue by shivaraj-bh** [LunarVim/LunarVim#4228] opened 2023-06-09 07:45 UTC
### Feature Description

I've been using lvim for over a year and I really like it. Recently, I've been working on creating a unified, reproducible configuration for all my machines using Nix. I want to manage my lvim configuration in Nix using home-manager and also install lvim via nixpkgs. I'm wondering if anyone has already done this or is currently working on it. If not, I'm willing to work on it myself. Let me know if this is something that others would find useful.

**Comment by LostNeophyte** [comment] 2023-06-09 08:23
duplicate of #1507

**Closed by LostNeophyte** 2023-06-09 08:23 UTC
Labels: enhancement
