### ISSUE TITLE
Support for brew and neovim v0.6

### ISSUE THREAD

**Issue by pynvimdev** [LunarVim/LunarVim#1929] opened 2021-11-08 10:23 UTC
### Feature motivation

I love using Luanrvim, but each time I have to manually install all the dependencies(Neovim v0.5, cargo etc). So adding support for brew would be helpful as it automatically install the dependencies

### Describe the expected solution

support for brew install

### Describe the alternatives you've considered

Maybe apt,aur etc

### Additional context

when I install neovimv.0.6 using brew, Luarvim was broken and not all configs were loaded. So support for neovim v.0.6 would be appreciated. Also what about adding Lspsaga as a plugin. It provides a nice gui for lsp.

**Comment by kylo252** [comment] 2021-11-08 19:17
Duplicate of #1021

You can also use the bundled installation script https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/install-neovim-from-release which can also be triggered as a make target.
https://github.com/LunarVim/LunarVim/blob/ee4d580bb2e1dbe7fdb90e8dca5d6296a50eba53/Makefile#L7

**Closed by kylo252** 2021-11-08 19:17 UTC
Labels: enhancement, packaging
