### ISSUE TITLE
Error detected while processing VimEnter Autocommands for "*" (Fresh install)

### ISSUE THREAD

**Issue by basava70** [LunarVim/LunarVim#4015] opened 2023-04-08 22:15 UTC
### Problem description

Fresh Install of lunarvim.
![Screenshot from 2023-04-09 00-11-43](https://user-images.githubusercontent.com/124213816/230744633-26824b10-0b28-4328-9b3e-d497bd525893.png)

I added the path in zshrc and i got this error at the launch when i press lvim
![Screenshot from 2023-04-09 00-06-16](https://user-images.githubusercontent.com/124213816/230744658-2068971b-8fe2-4f08-9177-084e4c1187e0.png)

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Terminal name

Gnome terminal (it happened with tmux and outside tmux as well)

### Operating system/version

Ubuntu 22.04

**Comment by basava70** [comment] 2023-04-08 23:07
I found a few more people with the same error after fresh install in r/lunarvim.
I have also seen a similar problem here
https://github.com/LunarVim/LunarVim/issues/2139
but it didnt solve my issue.
Please help us so we can use this awesome version of Neovim :)

**Comment by bk-software** [comment] 2023-04-09 04:29
have the same problem just installed it today

**Comment by LostNeophyte** [comment] 2023-04-09 17:22
> Neovim version (>= 0.8.0)
NVIM v0.8.3

are you sure that's your neovim version and not nightly?

**Comment by drumbsd** [comment] 2023-04-09 17:51
If can help, I got this exact same error after upgrading neovim from 0.8.3 to 0.9.0 on my mac. So I guess something that changes from nvim 0.8 to 0.9 break some things.

**Comment by schch88** [comment] 2023-04-09 19:30
Hello, I got this error too, and after reading what @LostNeophyte said, I confirmed that my neovim version is 0.9, which is the default version now. So I just installed the lvim nightly (which is the right one for neovim 0.9) and everything is working as it should...

**Comment by ctarx** [comment] 2023-04-10 05:53
I have the same problem on version: NVIM v0.10.0-dev [#4003](https://github.com/LunarVim/LunarVim/issues/4003#issuecomment-1495355150)

**Comment by LostNeophyte** [comment] 2023-04-10 06:52
lvim 1.2 is made for nvim 0.8, it won't work correctly with nvim nightly

**Comment by ctarx** [comment] 2023-04-10 10:26
> lvim 1.2 is made for nvim 0.8, it won't work correctly with nvim nightly

Thank you for reminding me about the compatibility issue between LunarVim 1.2 and Neovim nightly. I appreciate the heads up.

Regarding my previous message, I want to clarify that I was using Neovim v0.10.0-dev which was causing the problem. After  @LostNeophyte suggestion, I downgraded to Neovim 0.8.0+ and can confirm that LunarVim is now working correctly without any issues.

**Comment by basava70** [comment] 2023-04-10 11:20
> > Neovim version (>= 0.8.0)
> > NVIM v0.8.3
> 
> are you sure that's your neovim version and not nightly?, what's the output of `:!nvim --version` from lunarvim?

It is 0.8.3 as mentioned.

**Comment by basava70** [comment] 2023-04-10 11:22
> lvim 1.2 is made for nvim 0.8, it won't work correctly with nvim nightly

So, I have to change my Neovim to 0.8.0?

**Comment by LostNeophyte** [comment] 2023-04-10 11:28
> > lvim 1.2 is made for nvim 0.8, it won't work correctly with nvim nightly
> 
> So, I have to change my Neovim to 0.8.0?

open lvim, run :PackerSync, restart lvim, :TSUpdateSync, restart lvim and if that won't fix it then change to 0.8.1, but 0.8.3 should work, it doesn't use vimdoc afaik

**Comment by dhollinger** [comment] 2023-04-10 14:39
> lvim 1.2 is made for nvim 0.8, it won't work correctly with nvim nightly

NeoVim release v0.9.0 to stable in the last week. I started running into this as well since Neovim is managed by my package manager and updated when the neovim stable was updated.

**Comment by geralfonso** [comment] 2023-04-10 23:38
I'm having the same issue after updating neovim to v0.9.0. on mac.

**Comment by jiangwenqiang** [comment] 2023-04-10 23:38
```
cd  ~/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter
git pull origin master
```
it is works for me

**Comment by luzhenfang** [comment] 2023-04-15 09:03
use the Nightly version!

**Closed** 2023-05-08 16:54 UTC
Labels: bug

**Comment by juanandresgs** [comment] 2023-05-14 09:31
> ```
> cd  ~/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter
> git pull origin master
> ```
> 
> it works for me

Fixed it for me, thank you.

**Comment by NotReallyEight** [comment] 2023-05-14 11:59
A new version has been released, so you may want to upgrade to that instead of using that temporary fix.

**Comment by bitroniq** [comment] 2023-05-18 10:17
Did the trick for me:
```
cd .local/share/lunarvim/site/pack/packer/start/nvim-treesitter
git pull origin master
git checkout master
git pull
lvim
```
