### ISSUE TITLE
LVIM unexpected argument -u found

### ISSUE THREAD

**Issue by shaun-mathew** [LunarVim/LunarVim#4218] opened 2023-06-02 20:01 UTC
### Problem description

1. Install bob and use nightly version of neovim with bob (https://github.com/MordechaiHadad/bob) use nightly
2. Run nightly lunarvim install script
3. Receive the following error:
You can start LunarVim by running: /home/shaun/.local/bin/lvim
make: Leaving directory '/home/shaun/.local/share/lunarvim/lvim'
Creating desktop file
Preparing Lazy setup
error: unexpected argument '-u' found
4. Running lvim -u produces the following error
error: unexpected argument '-u' found

Usage: lvim <COMMAND>

For more information, try '--help'.

Additional Info:
I have already uninstalled lunarvim using the uninstall script and tried reinstalling but the problem persists. I don't get the unrecognized error when using nvim with the -u command. 

### LunarVim version

master

### Neovim version (>= 0.9.0)

NVIM v0.10.0-dev-429+g9f3c4c152

### Terminal name

kitty

### Operating system/version

Fedora 37

**Comment by kobzar** [comment] 2023-06-03 07:30
With stable neovim and stable branch situation the same?

**Comment by LostNeophyte** [comment] 2023-06-03 08:42
duplicate of https://github.com/LunarVim/LunarVim/issues/3612

**Closed by LostNeophyte** 2023-06-03 08:42 UTC
Labels: bug

**Comment by mu-us61** [comment] 2023-11-17 16:41
> With stable neovim and stable branch situation the same?

yes I have stable nvim and tried stable lvim gave same error , my nvim also installed by bob
