### ISSUE TITLE
Weird glitch when adding a new line code. 

### ISSUE THREAD

**Issue by stavyadatta** [LunarVim/LunarVim#3999] opened 2023-03-31 18:24 UTC
### Problem description

In a local setup on fedora 37, just add a new line and something like this happens while typing. I have no idea what is causing this. This does not happen in any arch based docker setup 
![Screenshot_20230331_234830](https://user-images.githubusercontent.com/62042596/229199594-ae03b51d-0697-4939-a004-8b78149a8611.png)

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.3

### Operating system/version

Fedora 37

**Comment by stavyadatta** [comment] 2023-03-31 18:26
The nvim statement is coming in between typing the code. Please help if possible. I honestly don't know how to really explain it. but while typing it just intermingles with the nvim comment I guess (what is that called)

**Comment by LostNeophyte** [comment] 2023-03-31 18:36
8th duplicate of https://github.com/LunarVim/LunarVim/issues/3481, which is also a duplicate, did you search through the existing issues?

**Closed by LostNeophyte** 2023-03-31 18:36 UTC
Labels: bug
