### ISSUE TITLE
[Feature]: formatting issues

### ISSUE THREAD

**Issue by eleijonmarck** [LunarVim/LunarVim#1600] opened 2021-09-22 09:11 UTC
### Feature motivation

I spent quite some time looking and searching for an answer on how to configure "prettier" for typescript.

I thought it would be clear from the documentation or from the example configuration.

If this is a true out of the box solution. Is it possible to add "prettier" or "eslint" for formatting on save when you add the LSP as well.

the information is there https://www.lunarvim.org/languages/typescript.html and once I figured out that I should just add this line to the configuration it worked.

```lua
-- Language configuration
-- exe value can be "prettier", "prettierd", "eslint", or "eslint_d"
lvim.lang.typescript.formatters = { { exe = "prettier" } }
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters

-- exe value can be "gofmt", "goimports", or "gofumpt"
lvim.lang.go.formatters = {{ exe = "goimports" }}

-- exe value can be "rustfmt"
lvim.lang.rust.formatters = { { exe = "rustfmt" } }
```

### Describe the expected solution

Installing or very clear documentation on the configuration of this.

Currently I found that it was quite unclear from the documentation.
Maybe add more examples in the example configuration for how to setup "linting" and "formatting"

Sorry that I am being a perfectionist. But this product is amazing and I just want it to be AMAZING and "just work" out of the box.
Many of my friends have moved away from it as VScode gets them up and running with formatting on save directly.

**Comment by abzcoding** [comment] 2021-09-22 11:16
i though this is clear enough 🤔 
https://www.lunarvim.org/languages/javascript.html#install-syntax-highlighting
<img width="868" alt="Screen Shot 2021-09-22 at 2 46 21 PM" src="https://user-images.githubusercontent.com/10992695/134334089-9d10e859-7abe-43a1-80ac-1ecdc35120f6.png">

**Comment by abzcoding** [comment] 2021-09-22 11:17
or even running `:LvimInfo`
<img width="980" alt="Screen Shot 2021-09-22 at 2 47 19 PM" src="https://user-images.githubusercontent.com/10992695/134334237-2d2c159b-2424-4d25-b5db-610b025f8a62.png">

**Comment by abzcoding** [comment] 2021-09-22 11:18
how can we make this more clear 🤔

**Comment by eleijonmarck** [comment] 2021-09-22 14:11
@abzcoding i think maybe adding it to the Quick Start or something.
Cause I was expecting `format_on_save` when I was saving my files.
I guess that setting is set. So I would "assume" (being a douche and all) that all the formatting and linting would be saved and settled through the installation process.

**Comment by abzcoding** [comment] 2021-09-22 14:14
😅 i mean the problem is that some servers doesn't have support for formatting so `format_on_save` doesn't work by default for them, so you have to configure those extra stuff, for example typescript
<img width="807" alt="Screen Shot 2021-09-22 at 5 44 08 PM" src="https://user-images.githubusercontent.com/10992695/134360371-e5271333-6164-4a06-8900-a75fb30d10a9.png">

but i would really appreciate it if you could create a PR for it in https://github.com/lunarVim/lunarvim.org

**Comment by eleijonmarck** [comment] 2021-09-22 15:02
@abzcoding do we have a way of checking if "formatting" is set for the user when we start `lunarvim`.
If formatting is not available for the LSP for that language, check if formatting is set; otherwise prompt for user to set it.

**Comment by eleijonmarck** [comment] 2021-09-22 15:11
I will for sure raise a PR for adding it to the docs!

**Comment by abzcoding** [comment] 2021-09-22 15:14
> @abzcoding do we have a way of checking if "formatting" is set for the user when we start `lunarvim`.
> If formatting is not available for the LSP for that language, check if formatting is set; otherwise prompt for user to set it.

yes using 
```lua
if client.resolved_capabilities.document_formatting then
```
 we can check if the lang server supports native formatting or not and using
```lua
local null_ls = require "lsp.null-ls"
local registered_providers = null_ls.list_supported_provider_names(ft)
if #registered_providers == 0 then
```
we can check if the user has set any formatter or not

**Comment by abzcoding** [comment] 2021-09-22 15:17
basically, look at (info.lua)[https://github.com/LunarVim/LunarVim/blob/rolling/lua/core/info.lua] 😅

**Comment by eleijonmarck** [comment] 2021-09-22 15:35
@abzcoding thank you soooo much for all the help. I will look at this when I am home and got some time over!!!

**Comment by eleijonmarck** [comment] 2021-09-23 11:08
@abzcoding sorry for the noob question. But I am having a hard time to setup lvim locally.
I have cloned and running `make install` when I am changing the line on description for the dashboard. Just to see that I can compile it.

```
  hello Configuration      "
```
Is there some other way to setup lvim locally?

**Comment by eleijonmarck** [comment] 2021-09-23 11:10
https://www.lunarvim.org/dev/#official-documentation this only points to learning lua programming language

**Comment by abzcoding** [comment] 2021-09-23 11:29
you don't need to build anything
just link your local fork of lunarvim to `~/.local/share/lunarvim/lvim`
and open `lvim`, that way you can see the differences as you are developing it

**Comment by abzcoding** [comment] 2021-09-23 11:31
<img width="815" alt="Screen Shot 2021-09-23 at 3 00 04 PM" src="https://user-images.githubusercontent.com/10992695/134499506-dd5acae5-e076-49f3-aeeb-24a459e23d20.png">
here is what i have
and when i want to develop sth, i just do 
```sh
cd ~/.local/share/lunarvim
mv lvim lvim_back
mv lvim_dev lvim
lvim
```
and after my development is finished and i want to go back, i do 
```sh
cd ~/.local/share/lunarvim
mv lvim lvim_dev
mv lvim_back
lvim
```

**Comment by abzcoding** [comment] 2021-09-23 11:31
btw hop on discord, if you have any questions

**Comment by abzcoding** [comment] 2021-09-23 11:32
i'm closing this, bcz instead of an issue description, its turning into a chat room 😅

**Closed by abzcoding** 2021-09-23 11:32 UTC
Labels: enhancement
