### ISSUE TITLE
Autocomplete removes closing brackets!

### ISSUE THREAD

**Issue by jmoloko** [LunarVim/LunarVim#2876] opened 2022-08-03 15:35 UTC
### Problem description

Autocomplete removes closing brackets!
Enrage!
Tell me please how to fix it?

Thanks!

### LunarVim version

master-b04aefb

### Neovim version (>= 0.7)

v0.7.2-3

### Operating system/version

ArchLinux

### Affected language servers

all

### Actual behavior

autocomplete removes closing brackets

### support info

LspInfo
![LspInfo](https://drive.google.com/file/d/1zq4gFs7yrCDcxs1WFvVMfYLC1qSmsWW7/view?usp=sharing)

LvimInfo
![LvimInfo](https://drive.google.com/file/d/1msxqfky3m2BZEfrnlnG5Ow43aKzZmU-u/view?usp=sharing)

**Comment by rebuilt** [comment] 2022-08-03 16:25
It's hard to diagnose an error like this with the information you provided.  

Did you try running a blank `~/.config/lvim/config.lua` file to confirm it's a problem with Lunarvim and not with your configuration?  

The `windwp/nvim-autopairs` plugin provides the autoclosing behavior in LunarVim.  Is that plugin running?   When you run `:PackerStatus`, does it show up on the list?  Are you modifying the behavior of autopairs at all?   

What filetype are you editing?   Do you have a language server enabled?  Did you install the treesitter parser for your language?  Are you getting any error messages?  Is there anything relevant in the error logs?  Does it affect all kinds of bracket pairings?  `(),[],{},'', ""` etc.

**Comment by jmoloko** [comment] 2022-08-03 18:39
Hi!
The problem is not in `~/.config/lvim/config.lua`, I tried without it.
`windwp/nvim-autopairs` - installed and working, but the problem is not in this plugin. This bug exists both with a plugin and without a plugin. I tried different.
>* What filetype are you editing?  - `main.go`  
>* Do you have a language server enabled? - **Yes**
>* Did you install the treesitter parser for your language? - **Yes**
>* Are you getting any error messages? - **Yes**
>*  Is there anything relevant in the error logs? - **No**
>* Does it affect all kinds of bracket pairings? - is not a fact... I know for sure - `(),[],{}`

I think the problem is not in my configuration, but in vanilla LunarVim.

**Comment by rebuilt** [comment] 2022-08-03 19:13
> Are you getting any error messages? - Yes

What's the error message you're getting? 

Also, I think maybe I missed something.  When you say the closing brackets get removed, when does that happen?  Is that when you're cycling through the completion options with tab and select an option?  Or does it happen when you save and your code autoformats?   Or maybe you mean that as you type, the closing bracket never get input at all.  Or perhaps you mean that the the closing bracket does get inserted, but as you continue typing, it disapears on a keypress.  Or maybe it means that the closing brackets disapears when you press escape to exit insert mode.   

I've just test go with the rolling release.  It seems to work.  This is what it looks like for me:

![go](https://user-images.githubusercontent.com/16025007/182688898-8f03718e-719a-49a9-9c7d-8e81f991872c.gif)

**Comment by jmoloko** [comment] 2022-08-03 19:18
About the error - I misunderstood you, there are no errors.
The bracket disappears when I select the desired autocomplete, when I press enter

**Comment by rebuilt** [comment] 2022-08-03 19:35
That's going to be handled by the `cmp` plugin.  We did make a recent change to the tab behavior of cmp.   Let's make sure packer isn't trying to use an outdated compile information for cmp.  Remove the `~/config/lvim/plugin` folder and run `:PackerCompile` or `:PackerSync` to regenerate the compile file.  

I can't reproduce the bug with `c := []bytes(fmt.Println(bytes)` on rolling.  

I also don't really have the time to test the current master branch.  I think kylo will push to master soon anyway so rolling and master will be the same either this week or next.  You can try installing the rolling branch to see if it fixes the problems for you.   Just remember to make a backup of you config if you're going to be installing another branch.

**Comment by jmoloko** [comment] 2022-08-03 19:37
![Brackets](https://drive.google.com/file/d/17CjBnHhShDgJPpqQf6Wza1iimeDipuh8/view?usp=sharing)

**Comment by rebuilt** [comment] 2022-08-03 19:39
Clicking on that link just says `Non-Image content-type returned`

**Comment by jmoloko** [comment] 2022-08-03 19:46
Sorry!
![](https://media.giphy.com/media/OjJuOFiP3vgsUuO0pJ/giphy.gif)

**Comment by rebuilt** [comment] 2022-08-03 20:03
Ok. I see.  I can reproduce that on rolling.

**Comment by jmoloko** [comment] 2022-08-03 20:06
> Remove the ~/config/lvim/plugin folder and run :PackerCompile or :PackerSync to regenerate the compile file.

I did it, the problem is still there

**Comment by rebuilt** [comment] 2022-08-03 20:58
It looks like the setup for both plugins has changed a little bit.  Can you add this to your `~/config/lvim/config.lua`  please.  Test it out and let me know if it fixes the bug.  

```lua
local cmp = require('cmp')
lvim.builtin.cmp.mapping["<CR>"] = cmp.mapping.confirm({ select = true })

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())

```



I'm not sure how this will affect luasnips.  The current behavior of `<CR>` has added logic to check for luasnip options.   

```
      ["<CR>"] = cmp.mapping(function(fallback)
        if cmp.visible() and cmp.confirm(lvim.builtin.cmp.confirm_opts) then
          if jumpable() then
            luasnip.jump(1)
          end
          return
        end

        if jumpable() then
          if not luasnip.jump(1) then
            fallback()
          end
        else
          fallback()
        end
      end),


```


Overriding `<CR>` seems not to break snippet autocompletion.  I'm not sure why.

**Comment by jmoloko** [comment] 2022-08-03 21:05
```lua
local cmp = require('cmp')
lvim.builtin.cmp.mapping["<CR>"] = cmp.mapping.confirm({ select = true })

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
```
Thank you so much! It worked!

**Comment by rebuilt** [comment] 2022-08-03 21:15
@kylo252 Our setup for cmp and autopairs no longer matches the README for those plugins.   `cmp` now provides a snippets table in the setup options.  Maybe that's the best place to put the luasnip logic?   

```lua
 cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      end,
    },
```

And autopairs now provides an event callback for cmp integration

```lua
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
```

**Comment by jmoloko** [comment] 2022-08-03 21:26
Tell me please, what to do with auto-indent brackets?
Do I need to create a new topic?
![](https://media.giphy.com/media/8siKLYPY2zHmNx7K3T/giphy.gif)

**Comment by rebuilt** [comment] 2022-08-04 00:45
Yes, please open another issue for the indentation bug.

**Comment by kylo252** [comment] 2022-08-04 07:24
> @kylo252 Our setup for cmp and autopairs no longer matches the README for those plugins. `cmp` now provides a snippets table in the setup options. Maybe that's the best place to put the luasnip logic?

I've been saying that for a while, but I don't know a about some of what's going on there. Please open a PR so we can start fixing it.

**Comment by danielo515** [comment] 2022-08-12 12:43
I always experienced this problem using lunar vim, but indeed it look it got worse on the latest rolling version. Did the suggested changes fixed the problem?

**Comment by rebuilt** [comment] 2022-08-12 12:59
> Did the suggested changes fixed the problem?

Yes

**Comment by smonsec** [comment] 2022-08-16 16:00
Happened with me, in .md file too. For example, if I'm adding a image file path, auto completing path with lsp suggestions will remove the closing small bracket and becomes something like this.....

![Some info](./path/to/file

**Comment by lvimuser** [comment] 2022-08-19 21:16
Didn't we purposely removed the autopairs thing a while back?
@smonsec @jmoloko try https://github.com/hrsh7th/nvim-cmp/pull/1140

**Closed** 2022-08-29 11:53 UTC
Labels: bug
