### ISSUE TITLE
LVim Builtin WhichKey Bug because of internal use of Lvim API

### ISSUE THREAD

**Issue by MatthewCushing** [LunarVim/LunarVim#3061] opened 2022-09-22 03:46 UTC
### Problem description

It is currently not possible (or at least not possible the way it is documented) to use LunarVim's WhichKey API to overwrite or modify table `e`.  This mapping currently toggles nvim-tree and, in WhichKey, is labeled "Explorer".

I decided to check out the nvim-tree setup file at `~/.local/share/lunarvim/lua/lvim/core/nvimtree.lua` and found this on line 167:
```lua
lvim.builtin.which_key.mappings["e"] = { "<cmd>NvimTreeToggle<CR>", "Explorer" }
```

Shouldn't this be set in the WhichKey file using the WhichKey API?  If it is wished to keep all mappings for plugins to be set in their personal config file, shouldn't WhichKey be called instead of using an API that I figured was intended for users to use externally?

On a more permanent solution, shouldn't the user's config at `~/.config/lvim/config.lua` have priority over internal use of the API?

**If the easy solution is okay to implement (move the mapping to WhichKey setup file or pull in WhichKey in the nvim-tree setup file) I can pick this one up and submit a PR real quick if this has a go ahead to change.**   

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

0.7.2

### Operating system/version

macOS 12.5

### Steps to reproduce

Remap table `e` that is exposed by the API 
```lua
lvim.builtin.which_key.mappings.e = {
  name = "Test",
  t = { "<cmd>lua print("test")<cr>", "Print Test" },
}
```

Create a table to hopefully overwrite the `e` table through the API (I believe this is identical to above except that it would also allow you to add a mapping that wasn't already defined?  Not a Lua expert)
```lua
lvim.builtin.which_key.mappings["e"] = {
  name = "Test",
  t = { "<cmd>lua print("test")<cr>", "Print Test" },
}
```

Redefining the entire mappings table through the API
```lua
lvim.builtin.which_key.mappings = {
  ["e"] = {
    name = "Test",
    t = { "<cmd>lua print("test")<cr>", "Print Test" },
  },
}
```
None of these work.

### support info

```console
# :LspInfo
 Language client log: /Users/cush/.cache/lvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 2, pid: 25688, bufnr: [14, 29])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/cush/.local/share/lunarvim/lvim
 	cmd:             lua-language-server
 
 1 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 10416, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Configured servers list: sumneko_lua
```

```console
# :LvimInfo

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   14
* treesitter status:       active

Active client(s)
* name:                      sumneko_lua
* id:                        1
* supported filetype(s):     lua
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              referencesProvider      | foldingRangeProvider      | documentFormattingProvider
                             definitionProvider      | typeDefinitionProvider    | documentRangeFormattingProvider
                             colorProvider           | hoverProvider             | documentSymbolProvider
                             workspaceSymbolProvider | documentHighlightProvider
* name:                      sumneko_lua
* id:                        2
* supported filetype(s):     lua
* attached buffers:          [14, 29]
* root_dir pattern:          [14, 29]
* capabilities:              referencesProvider      | foldingRangeProvider      | documentFormattingProvider
                             definitionProvider      | typeDefinitionProvider    | documentRangeFormattingProvider
                             colorProvider           | hoverProvider             | documentSymbolProvider
                             workspaceSymbolProvider | documentHighlightProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

**Comment by PaulosSouza** [comment] 2022-09-22 21:52
I think that is not only for `e`. I tried to overwrite the debug keymap `d` as you did and it didn't work

**Comment by lvimuser** [comment] 2022-09-24 13:27
duplicate of #2936

**Comment by ChristianChiarulli** [comment] 2022-10-09 08:04
https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/nvimtree.lua#L173
^^ everything like this should be moved to whichkey file and only set if the plugin is active

**Closed** 2022-10-11 09:04 UTC
Labels: bug, duplicate
