### ISSUE TITLE
Telescope's Ctrl + / on open panel throwing error "Invalid 'event': 'User TelescopeKeymap'"

### ISSUE THREAD

**Issue by eulersson** [LunarVim/LunarVim#4551] opened 2024-05-03 05:41 UTC
### Problem description

I was trying to run the keymaps for the telescope view, it shows them but an error `Invalid 'event': 'User TelescopeKeymap'` is thrown.

```
────────────────────────────────────────────────────────────────────────────── Insert Mode Keymaps ──────────────────────────────────────────────────────────────────────────────

    i -> <CR>    -> <anonymous>                     i -> <C-L>   -> complete_tag                    i -> <C-X>   -> select_horizontal
    i -> <C-N>   -> <anonymous>                     i -> <Down>  -> move_selection_next             i -> <C-T>   -> select_tab

[telescope.actions.which_key]: No name available for anonymous functions.
Error executing vim.schedule lua callback: ...k/lazy/opt/telescope.nvim/lua/telescope/actions/init.lua:1260: Invalid 'event': 'User TelescopeKeymap'
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        ...k/lazy/opt/telescope.nvim/lua/telescope/actions/init.lua:1260: in function <...k/lazy/opt/telescope.nvim/lua/telescope/actions/init.lua:1259>
Press ENTER or type command to continue
```

Related issues:

* https://github.com/nvim-telescope/telescope.nvim/issues/2734

### LunarVim version

release-1.3/neovim-0.9-d1c1bace-dirty

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

iTerm2

### Operating system/version

macOS 14.4.1 

### Steps to reproduce

1. Use a fresh LunarVim installation
2. Run any command that uses Telescope, for instance `<Leader>sh` to browse help files.
3. Press `Ctrl+/` to list the available keyboard shortcuts that you have available on that telescope view.

**Result**: It shows the mappings but an error along with them in `:messages` (that's why I couldn't copy paste it properly).
**Should**: Not throw that error.

### Screenshots

<img width="1792" alt="Screenshot 2024-05-03 at 07 14 12" src="https://github.com/LunarVim/LunarVim/assets/6486812/d2436ecd-2737-4365-ad49-0f582e96698c">

**Comment by kylo252** [comment] 2024-05-03 12:07
can you check which version of telescope you're one? It should be https://github.com/nvim-telescope/telescope.nvim/commit/d909568
`:Lazy log telescope.nvim`

I can't quite reproduce the issue since I don't have a dedicated key for `/` on my ISO keyboard (at least it doesn't seem to behave the same even with the layout set to US INTL), but `<C-h>` works for me when set manually:

```lua
local _, actions = pcall(require, "telescope.actions")
local _, builtin = pcall(require, "telescope.builtin")
lvim.builtin.telescope.defaults.mappings = {
  i = {
    ["<C-c>"] = actions.close,
    ["<C-j>"] = actions.cycle_history_next,
    ["<C-k>"] = actions.cycle_history_prev,
    ["<S-Up>"] = actions.cycle_previewers_prev,
    ["<S-Down>"] = actions.cycle_previewers_next,
    ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
    ["<CR>"] = actions.select_default + actions.center,
    ["<C-/>"] = actions.which_key,
    ["<C-h>"] = actions.which_key, -- keys from pressing <C-/>
    -- ["<C-i>"] = my_cool_custom_action,
  },
  n = {
    ["<C-c>"] = actions.close,
    ["<S-Up>"] = actions.cycle_previewers_prev,
    ["<S-Down>"] = actions.cycle_previewers_next,
    ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
    -- ["<C-Space>"] = custom_actions.fuzzy_filter_results,
    -- ["<C-i>"] = my_cool_custom_action,
  },
}
```

**Comment by eulersson** [comment] 2024-05-03 13:40
`:Lazy log telescope.nvim` tells me `9de317b` instead of `d909568`, why is that? 🤔

This is my LunarVim configuration: https://github.com/eulersson/dotfiles/blob/main/.config/lvim/config.lua

If I drop the snippet of lua you pasted on the top of my config.lua the issue persists when I do `<C-h>`, same error comes up. What is a good way to try without any of my stuff? When I tried to reproduce it I simply renamted `~/.config/lvim` to `~/.config/ignore-lvim`.

```
    ● telescope.nvim 29.89ms   ChatGPT.nvim
        dir    /Users/ramon/.local/share/lunarvim/site/pack/lazy/opt/telescope.nvim
        url    https://github.com/nvim-telescope/telescope.nvim
        branch 0.1.x
        commit 9de317b
        readme README.md
        help   |telescope.theprimeagen|
        help   |telescope.nvim|
        help   |telescope.changelog|
        cmd      Telescope 
  
      ✔ [task] log 54.99ms

```

**Comment by juicy-g** [comment] 2024-05-11 17:55
I can reproduce the issue in `release-1.3/neovim-0.9-d1c1bace` and I also get telescope version `9de317b` as per the snapshot of release 1.3, The issue doesn't occur in master so hopefully a new release will fix it.

**Comment by kylo252** [comment] 2024-05-15 07:59
Should be fixed in https://github.com/LunarVim/LunarVim/releases/tag/1.4.0

**Closed by kylo252** 2024-05-15 07:59 UTC
Labels: bug
