### ISSUE TITLE
Error on install in MacOS: failed to run `config` for mason.nvim

### ISSUE THREAD

**Issue by IanQS** [LunarVim/LunarVim#4037] opened 2023-04-14 00:08 UTC
### Problem description

When installing a fresh lunarvim (following the instructions) and on the most recent version of nvim, I run into the following error:

```
Initializing first time setupError detected while processing /Users/ianquah/.local/share/lunarvim/lvim/init.lua:
Failed to run `config` for mason.nvim
...nquah/.local/share/lunarvim/lvim/lua/lvim/core/mason.lua:113: attempt to call field 'setup' (a nil value)
# stacktrace:
  - ~/.local/share/lunarvim/lvim/lua/lvim/core/mason.lua:113 _in_ **setup**
  - ~/.local/share/lunarvim/lvim/lua/lvim/plugins.lua:27 _in_ **config**
  - ~/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:97
  - ~/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:95 _in_ **load**
  - ~/.local/share/lunarvim/lvim/init.lua:17Lazy setup complete
```

### LunarVim version

master-23ace671

### Neovim version (>= 0.8.0)

NVIM v0.10.0-dev-63+gf64f6706e-Homebrew

### Terminal name

iTerm

### Operating system/version

Ventura 13.2.1

### Steps to reproduce

0) Uninstall current lunarvim via

`bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh`

1) Clear your current configs

`mv ~/.config/lvim ~/.config/lvim_bu`

2) uninstall current nvim

`brew uninstall neovim`

3) install dev nvim

`brew install --HEAD neovim`

4) Install lvim

`bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`

and you should run into the issue I'm facing.

### Screenshots

<img width="937" alt="Screenshot 2023-04-13 at 4 54 05 PM" src="https://user-images.githubusercontent.com/6968573/231906983-bc691ddf-80c5-46c3-8cb6-c1110c4efbc6.png">

**Comment by kipintouch** [comment] 2023-04-14 05:18
Experiencing the same issue on `linux` with `neovim-0.9-release` and `lunarvim - master` branch
### Stacktrace
```
Failed to run `config` for mason.nvim
...nnnei/.local/share/lunarvim/lvim/lua/lvim/core/mason.lua:113: attempt to call field 'setup' (a nil value)
# stacktrace:
  - .local/share/lunarvim/lvim/lua/lvim/core/mason.lua:113 _in_ **setup**
  - .local/share/lunarvim/lvim/lua/lvim/plugins.lua:27 _in_ **config**
  - .local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:97
  - .local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:95 _in_ **load**
  - .local/share/lunarvim/lvim/init.lua:17Lazy setup complete
```

**Comment by LostNeophyte** [comment] 2023-04-14 19:31
duplicate of  #4024

**Closed by LostNeophyte** 2023-04-14 19:31 UTC
Labels: bug
