### ISSUE TITLE
Typescript does not working

### ISSUE THREAD

**Issue by expoure** [LunarVim/LunarVim#2983] opened 2022-09-02 14:47 UTC
### Problem description

When i try to go to definition this error occurs

![image](https://user-images.githubusercontent.com/12136268/188173841-f561edb7-0f2d-46b4-a15b-98ce812c9de9.png)

### LunarVim version

master-b3bcead

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

Pop_Os

### Affected language servers

tsserver

### Steps to reproduce

Open a ts file and try to go to definition or any other lsp thing

### Actual behavior

![image](https://user-images.githubusercontent.com/12136268/188173841-f561edb7-0f2d-46b4-a15b-98ce812c9de9.png)

### support info

![image](https://user-images.githubusercontent.com/12136268/188174847-c4e02f78-3ae6-4e2e-9eb9-b59a4539355c.png)

**Comment by mfcarneiro** [comment] 2022-09-03 05:32
Running some tests here after upgrading Lunar vim. First I installed the language servers again and did a LvimCacheReset.

Did you installed the language servers that you use and afterwards ran the :LvimUpdate ?

**Comment by dgabka** [comment] 2022-09-13 23:23
I am seeing similar behaviour. Upon opening a .js/.ts file I get a popup that a client has quit with exit code 1 and functionalities mentioned by @expoure are not working.
I don't have any custom settings for JS/TS, besides enabling prettier.

My version: rolling-7535f4e

**Comment by ChristianChiarulli** [comment] 2022-09-15 00:18
do you guys have `jsconfig.json` files?

**Comment by lvimuser** [comment] 2022-09-15 09:36
What's the output of `:LspLog` ?
cc @dgabka

**Comment by dgabka** [comment] 2022-09-26 10:07
```
[ERROR][2022-09-26 12:00:57] .../vim/lsp/rpc.lua:420	"rpc"	"typescript-language-server"	"stderr"	"/Users/dgabka/.local/share/nvim/mason/packages/typescript-language-server/node_modules/typescript-language-server/lib/cli.js:8\nimport { readFileSync } from 'node:fs';\n       ^\n\nSyntaxError: Unexpected token {\n    at Module._compile (internal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)\n"
```


For me the problem was that I was working on an older project that uses node 10 and I have it automatically selected whenever I enter project directory with fnm.
Once changed to node 16 the problem is solved.

@expoure please check this yourself

**Comment by ChristianChiarulli** [comment] 2022-10-05 01:52
closing since tsserver definitely works, this is not a bug.

**Closed by ChristianChiarulli** 2022-10-05 01:52 UTC
Labels: bug
