### ISSUE TITLE
Nvimtree becomes full screen after closing first opened buffer

### ISSUE THREAD

**Issue by Gonzalo9823** [LunarVim/LunarVim#2341] opened 2022-03-10 22:26 UTC
### Problem description

Hi!

I'm having this bug where when I have nvimtree open and I try to close the first opened file (using leader c) nvimtree uses all the space even tho there are other open files.

Steps to reproduce behavior:

1.- Open file
2.- Open another file from nvimtree
3.- Close the first file

Here's a relevant part of my config:

lvim.builtin.dashboard.active = true
lvim.builtin.notify.active = true
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "right"
lvim.builtin.nvimtree.show_icons.git = 0
lvim.builtin.nvimtree.setup.view.width = 40
lvim.builtin.nvimtree.setup.view.hide_root_folder = true
lvim.builtin.terminal.direction = "horizontal"
lvim.builtin.bufferline.options.show_buffer_close_icons = false
lvim.builtin.telescope.defaults = {
  sorting_strategy = "ascending",
  layout_config = {
    prompt_position = "top"
  }
}

### LunarVim version

1.1.2

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macOs 12.1

### Relevant log output

```shell
null-ls: require("null-ls.health").check()
========================================================================
  - OK: prettier: the command "/Users/gonzalo/Desktop/TGS/traceability-app/node_modules/.bin/prettier" is executable.
  - OK: fixjson: the command "fixjson" is executable.
  - OK: eslint: the command "/Users/gonzalo/Desktop/TGS/traceability-app/node_modules/.bin/eslint" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on darwin20.5.0.`
  - OK: **python3**: `Python 3.9.7`
  - OK: **node**: `v16.13.2`
  - OK: **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]`
  - OK: **Go**: `go version go1.17.2 darwin/arm64`
  - OK: **sh**: `Ok`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.2.22`
  - OK: **pip3**: `pip 21.2.4 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **npm**: `8.1.2`
  - OK: **javac**: `javac 16.0.1`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ‚úì ‚úì ‚úì ‚úì ‚úì 
  - yaml           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - java           ‚úì ‚úì . ‚úì ‚úì 
  - php            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - ruby           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - python         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - haskell        ‚úì . . . ‚úì 
  - rust           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - dot            ‚úì . . . ‚úì 
  - json           ‚úì ‚úì ‚úì ‚úì . 
  - javascript     ‚úì ‚úì ‚úì ‚úì ‚úì 
  - css            ‚úì . ‚úì ‚úì ‚úì 
  - lua            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - bash           ‚úì ‚úì ‚úì . ‚úì 
  - typescript     ‚úì ‚úì ‚úì ‚úì ‚úì 
  - html           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - tsx            ‚úì ‚úì ‚úì ‚úì ‚úì 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /opt/homebrew/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v16.13.2
  - INFO: Nvim node.js host: /Users/gonzalo/.nvm/versions/node/v16.13.2/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/gonzalo/.cache/nvim/lsp.log
  - INFO: Log size: 1 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for dot: ABI version 13
  - OK: Loaded parser for haskell: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
```

### Screenshots

![lvim](https://user-images.githubusercontent.com/5316653/157765219-daeaa5e8-1c38-48dd-bd68-29b85fdc43c0.gif)

**Comment by abzcoding** [comment] 2022-03-11 14:29
@Gonzalo9823 after nvim-tree becomes fullscreen, can you try hitting `<C-e>`  ( which means ctrl+e)
it seems to be somewhat related to https://github.com/kyazdani42/nvim-tree.lua/issues/1071
not entirely sure though

cc: @kylo252

**Comment by Gonzalo9823** [comment] 2022-03-11 15:55
@abzcoding after doing that it disappears and shows me the open file and if I press it again it shows the tree in the correct position.

After doing some more tests this only happens when you have 2 files open and close the first on the list.

**Comment by abzcoding** [comment] 2022-03-12 08:32
> @abzcoding after doing that it disappears and shows me the open file and if I press it again it shows the tree in the correct position.
> 
> After doing some more tests this only happens when you have 2 files open and close the first on the list.

yeah, it seems to be a nvim-tree related bug. We should keep this open until that is fixed

**Comment by kylo252** [comment] 2022-03-12 09:14
Duplicate of #2312

**Closed by kylo252** 2022-03-12 09:14 UTC
Labels: bug
