### ISSUE TITLE
[Bug]: This extension doesn't exist or is not ins talled: fzf

### ISSUE THREAD

**Issue by shaw991231** [LunarVim/LunarVim#1951] opened 2021-11-12 08:46 UTC
### Problem description

Hey guys! LunarVim is complaining about Telescope not having `fzf` installed on m1 mac. but i installed it through brew, i'm still getting some error when i use `lvim`:
```
packer.nvim: Error running config for telescope.nvim: .../start/telescope.nvim/l
ua/telescope/_extensions/init.lua:12: This extension doesn't exist or is not ins
talled: fzf

...k/packer/start/telescope-fzf-native.nvim/lua/fzf_lib.lua:11: dlopen(/Users/sh
aw/.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvim/lua/..
/build/libfzf.so, 0x0005): tried: '/Users/shaw/.local/share/lunarvim/site/pack/p
acker/start/telescope-fzf-native.nvim/lua/../build/libfzf.so' (no such file), '/
usr/local/lib/libfzf.so' (no such file), '/usr/lib/libfzf.so' (no such file), '/
Users/shaw/.local/share/lunarvim/site/pack/packer/start/telescope-fzf-native.nvi
m/build/libfzf.so' (no such file), '/usr/local/lib/libfzf.so' (no such file), '/
usr/lib/libfzf.so' (no such file)
```
I can also try `:! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make
` but getting error: 
```

rm -rf build
mkdir -p build
cc -O3 -Wall -Werror -fpic -std=gnu99 -shared src/fzf.c -o build/libfzf.so
In file included from src/fzf.c:5:
/usr/local/include/stdlib.h:134:25: error: pointer is missing a nullability type
 specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-co
mpleteness]
double   atof(const char *);
                         ^
/usr/local/include/stdlib.h:134:25: note: insert '_Nullable' if the pointer may
be null
double   atof(const char *);
                         ^
                          _Nullable
/usr/local/include/stdlib.h:134:25: note: insert '_Nonnull' if the pointer shoul
d never be null
double   atof(const char *);
                         ^
....

/usr/local/include/stdlib.h:161:57: note: insert '_Nullable' if the pointer may
be null
            int (* _Nonnull __compar)(const void *, const void *));
                                                               ^
                                                                _Nullable
/usr/local/include/stdlib.h:161:57: note: insert '_Nonnull' if the pointer shoul
d never be null
            int (* _Nonnull __compar)(const void *, const void *));
                                                               ^
                                                                _Nonnull
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [build/libfzf.so] Error 1
```

### LunarVim version

NVIM v0.5.1

### Neovim version (>= 0.5)

NVIM v0.5.1

### Screenshots

<img width="646" alt="CleanShot 2021-11-12 at 16 44 52@2x" src="https://user-images.githubusercontent.com/50760060/141437666-5adfe8b7-d86b-40c9-a056-ac22a9640087.png">
<img width="642" alt="CleanShot 2021-11-12 at 16 45 08@2x" src="https://user-images.githubusercontent.com/50760060/141437694-0104ec90-20c7-4b06-911a-2f3e823dcdd7.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by chase** [comment] 2021-11-13 04:17
@kylo252 This is exactly what you were talking about 😅

**Comment by chase** [comment] 2021-11-13 04:19
@shaw991231 If you modify the Makefile and drop `-Werror` you should be able to get it compiled

**Comment by kylo252** [comment] 2021-11-13 07:55
Duplicate of #1804

Please follow the instructions and discussion there.

**Closed by kylo252** 2021-11-13 07:55 UTC
Labels: bug
