### ISSUE TITLE
Serious issue if you create new tmux pane when you are already in tmux zoom mode

### ISSUE THREAD

**Issue by c02y** [LunarVim/LunarVim#2221] opened 2022-01-29 17:49 UTC
### Problem description

1. use default lvim config
2. open tmux, open 2 panes
3. zoom one pane
4. open lvim with a file
5. crate a new tmux pane

Check the lvim pane, the text is a mess, can not be restored, can not do anything inside the lvim, AND the memory for the lvim instance is rapidly increasing. (Check the gif screenshot)

### LunarVim version

2fa176f

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Arch Linux

### Relevant log output

```shell
`:checkhealth`


null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/chz/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 50
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.2`
  - OK: **node**: `v17.3.0`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **Go**: `go version go1.17.6 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.3.5`
  - OK: **npm**: `8.3.2`
  - OK: **pip3**: `pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - cmake          ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - make           ✓ . . . ✓ 
  - java           x ✓ . x x 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            x x x x x 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - cpp            x x ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: java(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2073
  - ERROR: java(indents): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 239
  - ERROR: java(injections): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2
  - ERROR: lua(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 503
  - ERROR: lua(locals): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 15
  - ERROR: lua(folds): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 92
  - ERROR: lua(indents): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 29
  - ERROR: lua(injections): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid field at position 18
  - ERROR: cpp(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 3277
  - ERROR: cpp(locals): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 1938

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /usr/sbin/python3
  - INFO: Python version: 3.10.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.3.0
  - INFO: Nvim node.js host: /home/chz/.npms/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/chz/.cache/nvim/lsp.log
  - INFO: Log size: 475 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for ninja: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
```

### Screenshots
![Peek 2022-01-30 01-44](https://user-images.githubusercontent.com/2135996/151671726-f05f38ea-b7fe-4409-9e34-19ff8b7cbf9e.gif)

**Comment by abzcoding** [comment] 2022-01-29 17:53
duplicate of https://github.com/LunarVim/LunarVim/issues/2174

**Comment by abzcoding** [comment] 2022-01-29 17:54
https://github.com/LunarVim/LunarVim/issues/2174#issuecomment-1016208376

**Comment by c02y** [comment] 2022-01-29 19:30
No, I don't think it is duplicated, I already read the issue before I posted this issue.

And I tried the solution in the comment, it doesn't work.

**Comment by c02y** [comment] 2022-01-29 19:32
BTW: nvim is working ok with vanilla/empty config, and it is working ok with my own config before using lunarvim

**Comment by abzcoding** [comment] 2022-01-29 19:32
first off can you do a `:TSUpdate`, there are lots of treesitter errors in your checkhelth
```lua
## The following errors have been detected:
  - ERROR: java(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2073
  - ERROR: java(indents): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 239
  - ERROR: java(injections): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2
  - ERROR: lua(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 503
  - ERROR: lua(locals): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 15
  - ERROR: lua(folds): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 92
  - ERROR: lua(indents): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 29
  - ERROR: lua(injections): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid field at position 18
  - ERROR: cpp(highlights): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 3277
  - ERROR: cpp(locals): ...rtgX/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 1938
```

**Comment by abzcoding** [comment] 2022-01-29 19:32
also please try with vanilla lunarvim as well

**Comment by abzcoding** [comment] 2022-01-29 19:34
@kylo252 any ideas?

**Comment by c02y** [comment] 2022-01-29 19:39
The `:checkhealth` is from vanilla lunarvim, I already said in the reproduce steps.

The same problem happens after I `:TSUpdate`
```

null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/chz/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 50
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **python3**: `Python 3.10.2`
  - OK: **node**: `v17.3.0`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **Go**: `go version go1.17.6 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.3.5`
  - OK: **npm**: `8.3.2`
  - OK: **pip3**: `pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - ninja          ✓ . ✓ ✓ . 
  - make           ✓ . . . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /usr/sbin/python3
  - INFO: Python version: 3.10.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.3.0
  - INFO: Nvim node.js host: /home/chz/.npms/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/chz/.cache/nvim/lsp.log
  - INFO: Log size: 477 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for ninja: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps

```

**Comment by abzcoding** [comment] 2022-01-29 19:42
please add this to your `config.lua`
```lua
vim.lsp.set_log_level "debug"
```
reproduce the issue, and then check `~/.cache/nvim/lsp.log` and `~/.cache/nvim/lvim.log`

**Comment by c02y** [comment] 2022-01-29 19:54
The logs are the result of bug-reproduce-steps:

[lsp.log](https://github.com/LunarVim/LunarVim/files/7964478/lsp.log)
[lvim.log](https://github.com/LunarVim/LunarVim/files/7964479/lvim.log)

**Comment by abzcoding** [comment] 2022-01-29 21:30
can you try fixing  this in your tmux
```lua
 - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
```
and also run `:LvimCacheReset` once and reopen
tbh, i'm not sure what is causing this 🤔

**Comment by c02y** [comment] 2022-01-30 05:41
Already tried that before the post, didn't work.

Tried that again, here is the log:
[lvim.log](https://github.com/LunarVim/LunarVim/files/7965360/lvim.log)

`lsp.log` is empty, I start lvim without opening any file.

```
:checkhealth

null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/chz/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 50
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **javac**: not available
  - WARNING: **julia**: not available
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **python3**: `Python 3.10.2`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **Go**: `go version go1.17.6 linux/amd64`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **sh**: `Ok`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **node**: `v17.3.0`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.3.5`
  - OK: **npm**: `8.3.2`
  - OK: **pip3**: `pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /usr/sbin/python3
  - INFO: Python version: 3.10.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.3.0
  - INFO: Nvim node.js host: /home/chz/.npms/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : DEBUG
  - WARNING: Log level DEBUG will cause degraded performance and high disk usage
  - INFO: Log path: /home/chz/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for ninja: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps

```

**Comment by abzcoding** [comment] 2022-01-30 08:38
> Already tried that before the post, didn't work.

how am I supposed to know that 😅 when your health shows issues,
in the future, it might be easier to fix all of those and then post the issue

anyways, there seems to be an error there `Include 285...`
can you get that somehow, like using `:messages` or sth

<img width="67" alt="Screen Shot 2022-01-30 at 12 06 23 PM" src="https://user-images.githubusercontent.com/10992695/151692645-c73a33f4-56a9-465e-9a59-f11fb3a1522b.png">

**Comment by kylo252** [comment] 2022-01-30 19:54
My first suggestion is switch over from using fish as the default shell in neovim, ref: https://www.lunarvim.org/troubleshooting/#lunarvim-is-slow

Test that and also please share:
- tmux version and config
- terminal used
- does this happen with vanilla neovim as well?

**Comment by c02y** [comment] 2022-02-04 14:20
> anyways, there seems to be an error there `Include 285...` can you get that somehow, like using `:messages` or sth
> 
Sorry, unable to save the content of `:messages" into my clip manager using something like `let @+ = execute('messages')` , I got a screenshot:
![Uploading 2022-02-04_22-17.png…]()

**Comment by abzcoding** [comment] 2022-02-04 14:42
maybe that is why i am not getting it, because i've disabled barbar and i'm using akinsho/bufferline instead
can you try adding this to your config and check if the issue still exists or not?
```lua
lvim.builtin.bufferline.active = false
```
make sure that it removes the barbar.nvim plugin

**Comment by c02y** [comment] 2022-02-04 14:46
> My first suggestion is switch over from using fish as the default shell in neovim, ref: https://www.lunarvim.org/troubleshooting/#lunarvim-is-slow

Already tried `vim.opt.shell = "/bin/sh"` before the original post , it didn't work.
> 
> Test that and also please share:
> 
>     * tmux version and config
> 
tmux 3.2a

I tried to analyze my tmux line by line, it seems my binding of splitting window causes this problem:
```
bind v split-window -p 50 -h -c "#{pane_current_path}"
bind V split-window -h
```
The `v` binding which is used in my tmux.conf cause this problem, the `V` line works fine, I don't know why
since my tmux config works fine in both vanilla nvim and my nvim config before using lunarvim as I already said https://github.com/LunarVim/LunarVim/issues/2221#issuecomment-1024973073
```
BTW: nvim is working ok with vanilla/empty config, and it is working ok with my own config before using lunarvim
```

>     * terminal used
> 
>     * does this happen with vanilla neovim as well?

**Comment by abzcoding** [comment] 2022-02-04 14:48
> The v binding which is used in my tmux.conf cause this problem, the V line works fine, I don't know why

again barbar.nvim seems to be causing this, try the thing i mentioned

**Comment by c02y** [comment] 2022-02-04 14:51
> > The v binding which is used in my tmux.conf cause this problem, the V line works fine, I don't know why
> 
> again barbar.nvim seems to be causing this, try the thing i mentioned

Yes, I tried, the issue is gone, I guess this is the barbar.nvim issue, since after I split the window, maybe the width of the lvim window cannot be handled by barbar.nvim

**Comment by abzcoding** [comment] 2022-02-04 14:52
yep, @kylo252 what do you think about replacing `barbar.nvim` with `bufferline.nvim` i've never had any issues with it

**Comment by kylo252** [comment] 2022-02-04 16:12
> yep, @kylo252 what do you think about replacing `barbar.nvim` with `bufferline.nvim` I've never had any issues with it

I'm good with that. I've been daily driving for a while now without any noticeable issues 🙄

**Closed** 2022-02-07 17:22 UTC
Labels: bug
