### ISSUE TITLE
[Bug]: run nvim error

### ISSUE THREAD

**Issue by jicvi** [LunarVim/LunarVim#1676] opened 2021-10-04 05:45 UTC
### Feature motivation

                                                                                                                                       
Error detected while processing /home/test/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim.lua:97: module 'vim.uri' not found:
        no field package.preload['vim.uri']
        no file '~/vim/uri.lua'
        no file './vim/uri.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri.lua'
        no file '/usr/local/share/lua/5.1/vim/uri/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/uri.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/uri/init.lua'
        no file './vim/uri.so'
        no file '/usr/local/lib/lua/5.1/vim/uri.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/uri.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue

**Comment by kylo252** [comment] 2021-10-04 06:28
You probably need to update your Neovim installation.

**Comment by jicvi** [comment] 2021-10-04 06:46
@kylo252 
nvim --version
NVIM v0.6.0-dev+164-g50b30de20

**Comment by jicvi** [comment] 2021-10-04 06:58
@kylo252
![2021-10-04_02-40](https://user-images.githubusercontent.com/14210650/135806963-33f5eddc-ac8c-48f9-94e6-11c1258ee223.png)

**Comment by abzcoding** [comment] 2021-10-04 07:45
yes you should either update your neovim version ( you are currently on the Aug 20th version) or downgrade to `neovim 0.5.0 or 0.5.1 release`

**Comment by abzcoding** [comment] 2021-10-04 07:46
duplicate of all of these
https://github.com/LunarVim/LunarVim/issues/1646
https://github.com/LunarVim/LunarVim/issues/1575
https://github.com/LunarVim/LunarVim/issues/1562
https://github.com/LunarVim/LunarVim/issues/1516
https://github.com/LunarVim/LunarVim/issues/1499
https://github.com/LunarVim/LunarVim/issues/1484
https://github.com/LunarVim/LunarVim/issues/1484

**Closed by abzcoding** 2021-10-04 07:46 UTC
Labels: bug
