### ISSUE TITLE
colorscheme not honored when in zellij

### ISSUE THREAD

**Issue by tunix** [LunarVim/LunarVim#4226] opened 2023-06-06 22:01 UTC
### Problem description

Set colorscheme:

```
lvim.colorscheme = "lunar"
```

Start zellij session and open lvim. The colorscheme is not honored. If you set it at runtime (with Spc+s+c) or reload the config file, the colorscheme works. But once you restart lvim, it goes back to some other theme.

Outside of zellij session, this problem doesn't occur. Also when I'm in light mode, this problem doesn't happen.

### LunarVim version

release-1.3/neovim-0.9-0aea5a68

### Neovim version (>= 0.9.0)

NVIM v0.9.0

### Terminal name

Wezterm

### Operating system/version

Fedora Silverblue 38

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/47731/462b24c0-7371-4bef-86b0-a696646fac1b)

![image](https://github.com/LunarVim/LunarVim/assets/47731/93d62985-6af2-4b3e-8691-2bd519ff5548)

![image](https://github.com/LunarVim/LunarVim/assets/47731/7c2406d6-4f58-4efa-afe1-b5ebfee51b0a)

**Comment by LostNeophyte** [comment] 2023-06-07 06:26
this is most likely caused by the same thing as https://github.com/LunarVim/LunarVim/issues/4126 is. and it's probably fixed in nvim 0.9.1

**Closed by LostNeophyte** 2023-06-07 06:26 UTC
Labels: bug
