### ISSUE TITLE
I can't install LunarVim on my MacOS 13

### ISSUE THREAD

**Issue by sixgod-666-jpg** [LunarVim/LunarVim#4335] opened 2023-08-20 12:45 UTC
### Problem description

When I enter the install commend of LunarVim, nothing happened. All I get is just blank. I tried again and again. But I don't know why. Help me please

The result of iTerm2 is below:

<img width="889" alt="截屏2023-08-20 20 39 21" src="https://github.com/LunarVim/LunarVim/assets/78605439/bbd04791-7d3a-4507-8b48-07a0f3d01610">

### LunarVim version

1.3

### Neovim version (>= 0.9.0)

0.9.1

### Terminal name

iTerm2

### Operating system/version

macOS 13.4

### Screenshots

It's the screenshots:

<img width="889" alt="截屏2023-08-20 20 39 21" src="https://github.com/LunarVim/LunarVim/assets/78605439/c9cc2bc5-24dd-4772-a003-9b00b5f6399c">

**Comment by LostNeophyte** [comment] 2023-08-20 13:35
possible duplicate of https://github.com/LunarVim/LunarVim/issues/4220, can you access the link from the install command?

**Comment by sixgod-666-jpg** [comment] 2023-08-20 13:45
> 

I can access the link and it seems to have nothing to do with Internet.     cause I tried with VPN、without VPN.   I still can't install it.

**Comment by LostNeophyte** [comment] 2023-08-20 13:46
how long does it take for the command to finish?

**Comment by sixgod-666-jpg** [comment] 2023-08-20 14:05
> how long does it take for the command to finish?

No finish.    After I entered the command, the third line  (which is "goyadeMacBook~Pro ~  % ")  appeared immediately

**Comment by LostNeophyte** [comment] 2023-08-20 14:07
do you have the prerequisites installed? https://www.lunarvim.org/docs/installation#prerequisites

**Comment by LostNeophyte** [comment] 2023-08-20 14:10
does `LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh) --help` show the help message?

**Comment by sixgod-666-jpg** [comment] 2023-08-20 14:11
> LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh) --help

still nothing

**Comment by sixgod-666-jpg** [comment] 2023-08-20 14:12
> do you have the prerequisites installed? https://www.lunarvim.org/docs/installation#prerequisites

yes, i'm sure i installed evething needed

**Comment by LostNeophyte** [comment] 2023-08-20 14:13
does `curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh` print the script?

**Comment by sixgod-666-jpg** [comment] 2023-08-20 14:17
> curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh

still not

**Comment by LostNeophyte** [comment] 2023-08-20 14:21
feels like an internet issue. what if you remove the -s flag

**Comment by sixgod-666-jpg** [comment] 2023-08-20 14:35
> feels like an internet issue. what if you remove the -s flag

I got "Failed to connect to raw.githubusercontent.com:443", and i searched for it.  It works. Thankyou ! ! !

**Closed** 2023-08-20 14:36 UTC
Labels: bug
