### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by dvsociety** [LunarVim/LunarVim#2462] opened 2022-04-13 23:56 UTC
### Problem description

When starting I get the error of the image. 

If I do checkhealth, I have not recognized the "javac" installation, could it have something to do with it?

![pic-full-220413-2046-38](https://user-images.githubusercontent.com/102924958/163287851-cbfcc93a-6a60-4c3e-a562-a6b045493187.png)

### LunarVim version

Last

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Arch Linux 

### Relevant log output

```shell
Does not recognize javac
```

**Comment by dvsociety** [comment] 2022-04-14 00:17
Fix the javac thing but the initially mentioned error is still

**Comment by abzcoding** [comment] 2022-04-14 10:19
duplicate of https://github.com/LunarVim/LunarVim/issues/2460

check this comment -> https://github.com/LunarVim/LunarVim/issues/2460#issuecomment-1098318504

**Comment by abzcoding** [comment] 2022-04-14 10:19
cc: @kylo252 everybody is gonna get this error, we should probably merge `rolling` into `master`

**Closed by abzcoding** 2022-04-14 10:19 UTC
Labels: bug

**Comment by kylo252** [comment] 2022-04-14 11:57
> cc: @kylo252 everybody is gonna get this error, we should probably merge `rolling` into `master`

we probably need to update impatient first, I've made a branch to test it, but my benchmarks weren't showing very good results. I'm wondering if this workflow wouldn't work with lunarvim because of the rtp changes, could you give it a try?

https://github.com/kylo252/LunarVim/commit/8af81271a75c3050130dbb209d8b75c1e4efb966

**Comment by abzcoding** [comment] 2022-04-14 12:20
> > cc: @kylo252 everybody is gonna get this error, we should probably merge `rolling` into `master`
> 
> we probably need to update impatient first, I've made a branch to test it, but my benchmarks weren't showing very good results. I'm wondering if this workflow wouldn't work with lunarvim because of the rtp changes, could you give it a try?
> 
> [kylo252@8af8127](https://github.com/kylo252/LunarVim/commit/8af81271a75c3050130dbb209d8b75c1e4efb966)

I'm not sure if that is a good idea or not since chase basically tuned it for our use case
nevertheless, I'll test it and report back

**Comment by abzcoding** [comment] 2022-04-14 12:25
@kylo252 it is about 30 to 40 percent slower than our current situation 😢

**Comment by kylo252** [comment] 2022-04-14 16:15
> @kylo252 it is about 30 to 50 percent slower than our current situation 😢 

Yeah, that's what I was getting as well. can you test if bundling it again gives back the lost performance? so basically use the files from my fork to replace the current version on rolling, and keep calling it manually without relying on packer.


I'm wondering if it doesn't work to call it so late.

**Comment by kylo252** [comment] 2022-04-14 19:32
> lets merge #2243 and #2461 for now, we will get back to this

I'll try to sort it out by tomorrow, hopefully. I've merged rolling into master which should at least solve the more common issue from gitsigns.
