### ISSUE TITLE
Unable to find dependency [neovim] (from neovim Appimage)

### ISSUE THREAD

**Issue by tomleo** [LunarVim/LunarVim#2530] opened 2022-04-27 18:24 UTC
### Problem description

1. Install neovim via appimage
2. Run lvim install script

```
$ whereis nvim
nvim: /usr/local/nvim /usr/share/nvim /home/tom/.local/bin/nvim.appimage /usr/share/man/man1/nvim.1.gz

$ nvim -v
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

```

### LunarVim version

latest stable release

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

Ubuntu 20.04.4 LTS

### Relevant log output

```shell
Detecting platform for managing any additional neovim dependencies
[ERROR]: Unable to find dependency [neovim]
Please install it first and re-run the installer. Try: sudo apt install -y neovim
```

**Comment by abzcoding** [comment] 2022-04-27 19:17
duplicate of https://github.com/LunarVim/LunarVim/issues/2316

please refer to this comment -> https://github.com/LunarVim/LunarVim/issues/2316#issuecomment-1056981110

**Closed by abzcoding** 2022-04-27 19:17 UTC
Labels: bug

**Comment by tomleo** [comment] 2022-04-28 15:01
> duplicate of #2316
> 
> please refer to this comment -> [#2316 (comment)](https://github.com/LunarVim/LunarVim/issues/2316#issuecomment-1056981110)

Per that comment:

> My first guess is that you're adding an an alias to one shell (zsh) and expecting the other one (bash) to know about it as well, which wouldn't really work.

So this is different because I'm on Ubuntu and per my issue description, nvim is available in the bash shell

**Comment by abzcoding** [comment] 2022-04-28 16:28
> I was able to resolve the issue.
> 
> 
> 
> I moved the app image to `/usr/bin/nvim` then ran through all the `update-alternatives` commands. Then the install script was able to find neovim. Not sure why the install script didn't have all the path information appended via my bashrc file.

This is the code that we are running

```lua
if ! command -v nvim &>/dev/null; then
    print_missing_dep_msg "neovim"
    exit 1
fi
```

You can check the install.sh file, not sure why this weird issue happens on ubuntu with appimage

**Comment by jd-apprentice** [comment] 2024-07-25 00:42
> I was able to resolve the issue.
> 
> I moved the app image to `/usr/bin/nvim` then ran through all the `update-alternatives` commands. Then the install script was able to find neovim. Not sure why the install script didn't have all the path information appended via my bashrc file.

This worked for my thanks.

```shell
cp ~/Apps/nvim.AppImage /usr/bin/nvim
which nvim
/usr/bin/nvim
LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
```
