### ISSUE TITLE
[Bug]: Uninstaller quietly fails on macOS Monterey

### ISSUE THREAD

**Issue by ghost** [LunarVim/LunarVim#2034] opened 2021-12-05 05:26 UTC
### Problem description

1. Run the installer
2. Run the uninstaller
3. Nothing happens
4. Reinstall
5. Try to uninstall
6. Nothing happens

### LunarVim version

lunarvim-0.6.1

### Neovim version (>= 0.5)

neovim-0.5.1

### Relevant log output

```shell
When I `set -x` on the uninstall script I see the script bomb attempting to set `LVIM_BIN` with errors piped to /dev/null: 

./uninstall.sh
+ ARGS_REMOVE_BACKUPS=0
+ declare -r XDG_DATA_HOME=/Users/user/.local/share
+ declare -r XDG_CACHE_HOME=/Users/user/.cache
+ declare -r XDG_CONFIG_HOME=/Users/user/.config
+ declare -r LUNARVIM_RUNTIME_DIR=/Users/user/.local/share/lunarvim
+ declare -r LUNARVIM_CONFIG_DIR=/Users/user/.config/lvim
+ declare -r LUNARVIM_CACHE_DIR=/Users/user/.cache/nvim
++ which lvim
+ LVIM_BIN=
```

### Screenshots

No screenshot but you should add space for individuals to provide additional information in your bug template so I'm going to drop it here:

- Main is never executed
- When `LVIM_BIN` is manually set the script still quietly fails
- Because of the failure `bash uninstall.sh -h` produces no output

P.s. I lied about reading the WIki

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment] 2021-12-05 10:03
@kylo252 i think this has been fixed in `rolling`, we might wanna merge `rolling` into `master`

@0xc0000007b can you try running this instead of your current `uninstall.sh` ?
https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/uninstall.sh

**Comment by urgosxd** [comment] 2021-12-10 03:12
I can't reinstall too, the install and uninstall command bash no output

**Comment by flamedmg** [comment] 2021-12-12 13:14
It looks like it doesn't work
<img width="321" alt="image" src="https://user-images.githubusercontent.com/416393/145713804-479b06a1-d55f-4e8c-921d-bb9f71384d71.png">
I do not see all this:

**Comment by abzcoding** [comment] 2021-12-12 13:18
cc: @kylo252

**Comment by flamedmg** [comment] 2021-12-12 13:32
After several install/uninstal i can't use lvim anymore, getting this error during installation:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/416393/145714348-b151f7cd-0abd-4886-8dc9-68aa04fcc9f7.png">
```
Installing LunarVim shim
Preparing Packer setup
E484: Can't open file /share/nvim/syntax/syntax.vim[packer.nvim] [ERROR 15:30:49] async.lua:20: Error in coroutine: ...ack/...m(lua):E5108: Error executing lua vim.lua:99: module 'vim.uri' not found:[packer.nvim] ^Ino field package.preload['vim.uri'][packer.nvim] ^Ino file './vim/uri.lua'[packer.nvim] ^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/uri.lua'[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/vim/uri.lua'[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/vim/uri/init.lua'[packer.nvim] ^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/uri.lua'[packer.nvim] ^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/uri/init.lua'[packer.nvim] ^Ino file './vim/uri.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/vim/uri.so'[packer.nvim] ^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/uri.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'[packer.nvim] ^Ino file './vim.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/vim.so'[packer.nvim] ^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'[packer.nvim] stack traceback:[packer.nvim] ^I[C]: in function 'require'[packer.nvim] ^Ivim.lua:99: in function '__index'[packer.nvim] ^I.../pack/packer/start/nvim-lspconfig/lua/lspconfig/util.lua:4: in main chunk[packer.nvim] ^I[C]: in function 'require'[packer.nvim] ^I...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:1: in main chunk[packer.nvim] ^I[C]: in function 'require'[packer.nvim] ^I.../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:1: in main chunk[packer.nvim] ^I[C]: in function 'require'[packer.nvim] ^I[string ":lua"]:9: in main chunk[packer.nvim] ^I[C]: in function 'resume'[packer.nvim] ^I.../site/pack/packer/start/packer.nvim/lua/packer/async....function <.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:11>[packer.nvim] [ERROR 15:30:50] async.lua:20: Error in coroutine: ...ack/...ter.lua:2: nvim-treesitter requires a more recent Neovim nightly version![packer.nvim] stack traceback:[packer.nvim] ^I[C]: in function 'error'[packer.nvim] ^I...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:2: in main chunk[packer.nvim] ^I[C]: in function 'require'[packer.nvim] ^I[string ":lua"]:1: in main chunk[packer.nvim] ^I[C]: in function 'resume'[packer.nvim] ^I.../site/pack/packer/start/packer.nvim/lua/packer/async....function <.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:11>packer.compile: Complete
packer.nvim: Error running config for nvim-treesitter: .../.local/share/lunarvim/lvim/lua/lvim/core/treesitter.lua:79: attempt to call method 'get_default' (a nil value)
```

**Comment by kylo252** [comment] 2021-12-12 13:33
@flamedmg, please share the output of these commands
```sh
tail ./uninstall.sh
nvim --version
where lvim
```

**Comment by flamedmg** [comment] 2021-12-12 13:37
```
❯ tail ./uninstall.sh
function main() {
  parse_arguments "$@"
  echo "Removing LunarVim binary..."
  remove_lvim_bin
  echo "Removing LunarVim directories..."
  remove_lvim_dirs
  echo "Uninstalled LunarVim!"
}

main "$@"
```

```
❯ nvim --version
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1638296114063.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

```
❯ where lvim
/Users/dmg/.local/bin/lvim
```

**Comment by flamedmg** [comment] 2021-12-12 13:38
looks lime my neovim is corrupted. Now i realize that happened, when i used script mentioned on installation page of lunarvim and installed fresh neovim using it:
```
bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install-neovim-from-release)
```

**Comment by flamedmg** [comment] 2021-12-12 13:41
after removing nvim from ~/.local/bin it is installing fine again, but that means nvim installation script or nvim installed by it doing something wrong on macos

**Comment by flamedmg** [comment] 2021-12-12 13:45
Interesting, that now it loads just vare neovim without anyplugins, however i rememer it was installing them during first run
<img width="871" alt="image" src="https://user-images.githubusercontent.com/416393/145714845-f14be918-c0a0-474e-a733-6f74965da210.png">

**Comment by kylo252** [comment] 2021-12-12 13:55
Are you using an M1? That installation script doesn't check for the architecture, unfortunately. So what you're seeing might be some rosetta magic.

**Comment by flamedmg** [comment] 2021-12-12 13:57
No, I'm using usual intel mac and lunarvim was working just fine previously until i started to mess nvchad. I thought they are completely separate, but later found that they are using same cache folder. Since then installation finishes, but no plugins are installed automatically

**Comment by kylo252** [comment] 2021-12-12 14:05
LunarVim is _mostly_ independent of the neovim's default user-runtime. The problem is that some paths are hard-coded upstream, either by neovim itself or other plugins, to use `vim.fn.stdpath "cache"`, but that's basically it. I actually daily-drive my neovim config side-by-side with lvim's without a hitch.

**Comment by abzcoding** [comment] 2022-02-02 11:31
This is fixed in the `rolling` branch. Feel free to reopen if the issue persists

**Closed by abzcoding** 2022-02-02 11:31 UTC
Labels: bug
