### ISSUE TITLE
help command result in "Error detected while processing BufReadPost Autocommands for "*":"

### ISSUE THREAD

**Issue by Nunatic02** [LunarVim/LunarVim#3703] opened 2023-01-10 02:53 UTC
### Problem description

Type `:help [option]` or `:h [option]`  will result in error message below:

---
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:22: Error executing lua:
 ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:23: Vim(append):Error executing lua callback: ...im/0
.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 14 for language hel
p
stack traceback:
        [C]: in function '_ts_parse_query'
        ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...2/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:52: in function 'new'
        ...r/neovim/0.8.2/share/nvim/runtime/lua/vim/treesitter.lua:45: in function '_create_parser'
        ...r/neovim/0.8.2/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:34: in function 'start'
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:42: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/
lua/nvim-treesitter/configs.lua:130>
        [C]: in function 'nvim_cmd'
        ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:23: in function <...ocal/Cellar/neovim/0.8.2/s
hare/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:22: in function <...ocal/Cellar/neovim/0.8.2/s
hare/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:23: in function <...ocal/Cellar/neovim/0.8.2/s
hare/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:22: in function <...ocal/Cellar/neovim/0.8.2/s
hare/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...ocal/Cellar/neovim/0.8.2/share/nvim/runtime/filetype.lua:22: in function <...ocal/Cellar/neovim/0.8.2/s
hare/nvim/runtime/filetype.lua:11>
```

Tested on a fresh LunarVim install.

### LunarVim version

release-1.2/neovim-0.8-8f4a7bd

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

macOS 13.0

### Steps to reproduce

1. Install neovim with brew.
2. Install LunarVim from scratch.
3. type `:help clipboard-tool` or other help options.

### Screenshots

https://user-images.githubusercontent.com/58194485/211450414-725620ed-d87d-4b17-aa7f-4b9140966c65.mp4

**Comment by LostNeophyte** [comment] 2023-01-10 05:43
Duplicate of #3680

**Closed** 2023-01-10 05:43 UTC
Labels: bug
