### ISSUE TITLE
Elixir code with pattern matching in it leads to an `E121: Undefined variable` error then moving the cursor into the function body

### ISSUE THREAD

**Issue by ckruse** [LunarVim/LunarVim#3305] opened 2022-10-20 06:23 UTC
### Problem description

1. `mix new test`
2. edit `lib/test.ex`, add a function:
    ```
    def foo(_, %{args: args}, %{context: context}) do
      IO.inspect(args)
    end
    ```
3. Save file
4. move cursor into function body
5. Two errors appear: `E121: Undefined variable: args` and `E121: Undefined variable: context`

### LunarVim version

master-c015d0f

### Neovim version (>= 0.8.0)

v0.8.0

### Operating system/version

macOS 12.6

### Steps to reproduce

1. `mix new test`
2. edit `lib/test.ex`, add a function:
    ```
    def foo(_, %{args: args}, %{context: context}) do
      IO.inspect(args)
    end
    ```
3. Save file
4. move cursor into function body
5. Two errors appear: `E121: Undefined variable: args` and `E121: Undefined variable: context`

### support info

```console
Language client log: /Users/ckruse/.local/state/nvim/lsp.log
 Detected filetype:   elixir
 
 1 client(s) attached to this buffer: 
 
 Client: elixirls (id: 1, pid: nil, bufnr: [1])
 	filetypes:       elixir, eelixir, heex, surface
 	autostart:       true
 	root directory:  /Users/ckruse/test
 	cmd:             elixir-ls
 
 Other clients that match the filetype: elixir
 
 Config: tailwindcss
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         aspnetcorerazor, astro, astro-markdown, blade, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, haml, handlebars, hbs, html, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte
 	root directory:    Not found. Searched for: root_pattern('tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git').
 	cmd:               tailwindcss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: elixirls, tailwindcss
 ```

 ```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                elixir
* bufnr:                   1
* treesitter status:       active

Active client(s)
* name:                      elixirls
* id:                        1
* supported filetype(s):     [elixir, eelixir, heex, surface]
* attached buffers:          1
* root_dir pattern:          1
* capabilities:              implementationProvider | documentFormattingProvider | referencesProvider
                             documentSymbolProvider | hoverProvider              | macroExpansion
                             foldingRangeProvider   | workspaceSymbolProvider    | definitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: [mix, surface]

Linters info
* Active: 
* Supported: credo

Code actions info
* Active: 
 ```

### Screenshots

![Bildschirmfoto 2022-10-20 um 08 22 28](https://user-images.githubusercontent.com/175095/196871582-e53ca818-58d5-46e2-a85a-7ece4b49b925.png)

**Comment by Hermanverschooten** [comment] 2022-10-20 11:37
I am experiencing the same issue.

**Comment by ckruse** [comment] 2022-10-20 12:04
Ok, I had the time to do a bit of research. It looks like the `breadcrumb` module is the culprit. As soon as I disable it, everything works fine.

**Comment by Hermanverschooten** [comment] 2022-10-20 12:08
concur, adding `lvim.builtin.breadcrumbs.active = false` to my config, removes the errors.

**Comment by Hermanverschooten** [comment] 2022-10-20 12:50
I think it has something to do with this bug https://github.com/SmiteshP/nvim-navic/issues/65, notice that it only happens when there is a pattern match on a map.

**Comment by SmiteshP** [comment] 2022-10-25 16:35
Added a fix for this issue 👍🏽

**Comment by Hermanverschooten** [comment] 2022-10-26 07:49
I switched to master and am up to date with your changes, but I am still getting `E15: ongeldige expressie: "id" => id` as soon as I enter a function with a pattern match on a map. In this case the error is triggered by
```elixir
def handle_event("select", %{"id" => id}, socket) do
...
end
```
The breadcrumb at the top shows `handle_event("select, , socket)`

**Comment by dkarter** [comment] 2022-10-26 15:03
Same it didn't appear to fix the issue for me

**Comment by SmiteshP** [comment] 2022-10-26 15:52
@Hermanverschooten @dkarter Can you share the output of `get_data` when cursor is inside this function?

**Comment by dkarter** [comment] 2022-10-26 16:05
@SmiteshP 

```lua
{ {
    icon = " ",
    kind = 2,
    name = "IntegrationLoop.Accounts.DeactivateAccount",
    scope = {
      ["end"] = {
        character = 3,
        line = 75
      },
      start = {
        character = 0,
        line = 1
      }
    },
    type = "Module"
  }, {
    icon = " ",
    kind = 12,
    name = "defp update_account(%{fetch_account: %AccountSchema{} = account}, _args)",
    scope = {
      ["end"] = {
        character = 5,
        line = 65
      },
      start = {
        character = 2,
        line = 61
      }
    },
    type = "Function"
  } }
```

**Comment by SmiteshP** [comment] 2022-10-29 04:11
@dkarter @Hermanverschooten Can you check on the latest commit now?

**Comment by LostNeophyte** [comment] 2022-10-29 14:53
> Can you check on the latest commit now?

Works for me

**Closed** 2022-10-31 12:57 UTC
Labels: bug

**Comment by dkarter** [comment] 2022-11-02 21:45
@SmiteshP I'm still seeing this issue (or a variant of it) with the latest nvim-navic:

![Screenshot 2022-11-02 at 16 42 08@2x](https://user-images.githubusercontent.com/551858/199608046-1c80ca72-4531-4114-b12a-374677fd6ab5.png)

![Screenshot 2022-11-02 at 16 43 20@2x](https://user-images.githubusercontent.com/551858/199608234-1cb7e64b-414e-44b9-8089-46f4494e7994.png)

Also seems like navic is doing something weird to the text (`Plug.Conn` -> `Alllug.Conn`)

**Comment by Hermanverschooten** [comment] 2022-11-16 10:05
I can confirm that with master this is no longer an issue for me.
