### ISSUE TITLE
emmet_ls is not working with Html files.

### ISSUE THREAD

**Issue by ijouiri** [LunarVim/LunarVim#2703] opened 2022-06-08 16:13 UTC
### Problem description

the emmet_ls does not work.

### LunarVim version

master-3475f76

### Neovim version (>= 0.7)

NVIM v0.7.0

### Operating system/version

archlinux 5.18.1-arch1-1

### Affected language servers

html

### Actual behavior

![image](https://user-images.githubusercontent.com/57574897/172665045-47f7b881-6f23-49ef-8f14-151cb4783d42.png)

emmet_ls is not working with html

### support info

![image](https://user-images.githubusercontent.com/57574897/172665965-a4a057af-0b75-4d19-87d1-949e89bc928b.png)

**Comment by kobzar** [comment] 2022-06-08 18:00
Show screen of opened document with code and lualine please
And what are you mean NOT WORK
Wich action are you do ?(For repeat the issue)

**Comment by ijouiri** [comment] 2022-06-09 13:48
![image](https://user-images.githubusercontent.com/57574897/172862352-85cdad4c-c7b6-4ca9-bb46-5da28a13ddc8.png)
![image](https://user-images.githubusercontent.com/57574897/172862825-8d1520f6-ad40-4ec8-ad48-46c961c7ee03.png)


As you can see in this picture I've installed it, but it doesn't work with HTML files, i don't know why

**Comment by kylo252** [comment] 2022-06-10 11:49
Duplicate of #2152


`emmet_ls` is overridden (no automatic configuration) so you need to call the setup function manually, 

```lua
require("lvim.lsp.manager").setup("emmet_ls")
```

you should also check https://www.lunarvim.org/troubleshooting/#language-server-xxx-does-not-start-for-me

**Closed by kylo252** 2022-06-10 11:49 UTC
Labels: bug

**Comment by gwapocom** [comment] 2023-03-20 06:42
![image](https://user-images.githubusercontent.com/99315090/226265553-b61aaab6-4293-4472-964d-073396568c7b.png)
![image](https://user-images.githubusercontent.com/99315090/226265723-ec7d48a2-52cc-497b-bc84-eab5122f2c60.png)

emmet_ls is not working with html files
