### ISSUE TITLE
Mac (m1) install says ERR! path /opt/homebrew/bin/tree-sitter file already exisits

### ISSUE THREAD

**Issue by st203** [LunarVim/LunarVim#3738] opened 2023-01-16 13:30 UTC
### Problem description

Any suggestions on this? I installed Neovim 0.8  using brew. 

2 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New minor version of npm available! 9.2.0 -> 9.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.0
npm notice Run npm install -g npm@9.3.0 to update!
npm notice
npm ERR! code EEXIST
npm ERR! path /opt/homebrew/bin/tree-sitter
npm ERR! EEXIST: file already exists
npm ERR! File exists: /opt/homebrew/bin/tree-sitter
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

Looks like a great product btw, keep up the good work!

### LunarVim version

Release 1.2

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

m1 Mac ventura 13.1

### Steps to reproduce

Running your terminal command to install and opting in for NodeJs dependencies.

**Comment by LostNeophyte** [comment] 2023-01-16 14:17
> Looks like a great product btw, keep up the good work!

Thanks!

duplicate of #3119, I guess it works for some and not for others, will try to fix it but the fix won't make it to 1.2, for now just skip installing npm dependencies

**Comment by gravis** [comment] 2023-01-16 19:38
I have some issues with tree-sitter as well. I updated an existing lvim installation so the install script isn't the problem, but checkhealth is complaining:

```
 ## The following errors have been detected:
   - ERROR: vim(highlights): ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
     vim(highlights) is concatenated from the following files:
     | [ERROR]:"/Users/gravis/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

In the tree-sitter readme, there's a [troubleshooting section related to this](https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position):

> Make sure you don't have more than one parser runtime directory. You can execute this command :echo nvim_get_runtime_file('parser', v:true) to find all runtime directories. 

and `:echo nvim_get_runtime_file('parser', v:true)` indeed returns 2 paths in my case. This is because `tree-sitter` is installed as a dependency of `neovim` with homebrew. Which means the install script isn't the only part to fix here.

**Comment by LostNeophyte** [comment] 2023-01-16 20:57
> I have some issues with tree-sitter as well. I updated an existing lvim installation so the install script isn't the problem, but checkhealth is complaining:
> 
> ```
>  ## The following errors have been detected:
>    - ERROR: vim(highlights): ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
>      vim(highlights) is concatenated from the following files:
>      | [ERROR]:"/Users/gravis/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.2/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
> ```
> 
> In the tree-sitter readme, there's a [troubleshooting section related to this](https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position):
> 
> > Make sure you don't have more than one parser runtime directory. You can execute this command :echo nvim_get_runtime_file('parser', v:true) to find all runtime directories. 
> 
> and `:echo nvim_get_runtime_file('parser', v:true)` indeed returns 2 paths in my case. This is because `tree-sitter` is installed as a dependency of `neovim` with homebrew. Which means the install script isn't the only part to fix here.

Your problem is completely different, ts queries bundled with your neovim version are too old. Run TsUpdate or/and TsInstall <lang> '. If that won't help remove the bundled ones. See pinned issue on nvim-treesitter repo.

**Comment by gravis** [comment] 2023-01-17 00:21
Thanks for the info @LostNeophyte. Unfortunately, all my parsers are up-to-date already, as well as my lunarvim installation.
I'm not sure what's going on exactly, but I do have 2 paths for the parsers:

`['~/.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/parser', '/opt/homebrew/Cellar/neovim/0.8.2/lib/nvim/parser']`

and I get this error randomly when I start lunarvim. I understand the binary has nothing to do with that, but it seems the formula comes with extensions in `/opt/homebrew/Cellar/neovim/0.8.2/lib/nvim/parser`. I wonder if when the loading can take one of the other randomly.

**Closed** 2023-01-17 06:11 UTC
Labels: bug

**Comment by LostNeophyte** [comment] 2023-01-17 07:34
@gravis remove the bundled ones (opt/homebrew/Cellar/neovim/0.8.2/lib/nvim/parser) just delete everything in the directory. Every newer neovim installation has this folder

**Comment by gravis** [comment] 2023-01-17 15:37
@LostNeophyte I did that yesterday and the errors went away (also had to switch to a different colorscheme because `onedarker` seems to have issues with the latest lunarvim, but that's a different story). The problem is that every time `neovim` will be updated in homebrew, these files will come back as well.

**Comment by LostNeophyte** [comment] 2023-01-17 15:44
> @LostNeophyte I did that yesterday and the errors went away (also had to switch to a different colorscheme because `onedarker` seems to have issues with the latest lunarvim, but that's a different story). The problem is that every time `neovim` will be updated in homebrew, these files will come back as well.

Open a different issue, I'm no longer sure if that directory is the one I was thinking about earlier. Also I don't have a mac to troubleshoot, I'll try homebrew in podman but I'm not sure if the results will be the same
