### ISSUE TITLE
The filepath will appear in bufferline or lualine or input position or both  or any where 

### ISSUE THREAD

**Issue by ancion** [LunarVim/LunarVim#3592] opened 2022-12-11 12:44 UTC
### Problem description

The filepath will appear in bufferline or lualine or input position or both  or any where.
this issue only appear on fedora 37 but work well on Ubuntu22.04.

### LunarVim version

master

### Neovim version (>= 0.8.0)

NVIM v0.8.1

### Operating system/version

fedora37

### Steps to reproduce

lvim 
open any file 
enter insert mode 
input something  

### Screenshots

![屏幕截图_20221211_203459](https://user-images.githubusercontent.com/49437191/206904182-b15acd48-04e5-4ea8-b0bc-0602fcc52538.png)

**Comment by LostNeophyte** [comment] 2022-12-11 12:47
duplicate of https://github.com/LunarVim/LunarVim/issues/3481, there's a workaround there, have you checked existing issue? this one is pinned

**Closed by LostNeophyte** 2022-12-11 12:47 UTC
Labels: bug
