### ISSUE TITLE
Inserts/Displays strings when entering insert-mode and typing characters.

### ISSUE THREAD

**Issue by Moggel12** [LunarVim/LunarVim#3496] opened 2022-11-18 08:50 UTC
### Problem description

Steps to reproduce:
- Have LunarVim installed
- Upgrade Fedora 36 to Fedora 37

I really did not do anything else to my system in the meantime.

It seems like the strings inserted are metadata or statusline related strings like:
- [No Name] - NVIM
- filename + path/to/file - NVIM

Writing to the file while the strings are on-screen does not write these strings to the file, only the characters actually inserted, e.g. entering insert-mode on a line `x = 1 << n` may result in LunarVim displaying `x = [No Name] - NVIM` for which I could insert `+ b` and write to the file. The next time I open the file, the line would only contain `x = 1 << n + b` and not the "[No Name] - NVIM". The problem mainly is that I can't clearly read the line while inserting characters.

It also seems to occur when deleting characters with x in normal-mode. Possibly also other normal-mode editing commands.

### LunarVim version

release-1.2/neovim-0.8-886e3e4

### Neovim version (>= 0.8.0)

NVIM v0.8.0

### Operating system/version

Fedora 37

### Steps to reproduce

The problem does not occur using the minimal config.

### support info

LspInfo:
```console
Use [q] or [Esc] to quit the window
 
 Language client log: /home/mikkelvestergaard/.local/state/nvim/lsp.log
 Detected filetype:   
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: 
```
LvimInfo:
```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                
* bufnr:                   7
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active
```

### Screenshots

![lvim-isssue-0](https://user-images.githubusercontent.com/45975361/202660240-a4c294a2-1579-40bf-ac49-c83f50b7b116.png)
![lvim-isssue-1](https://user-images.githubusercontent.com/45975361/202659862-5cb0205b-8f47-41ce-851f-b9837673fa16.png)

**Comment by LostNeophyte** [comment] 2022-11-18 09:06
duplicate of #3481

**Closed by LostNeophyte** 2022-11-18 09:06 UTC
Labels: bug
