### ISSUE TITLE
Colorschemes broken due to #2359

### ISSUE THREAD

**Issue by sa-mendez** [LunarVim/LunarVim#2368] opened 2022-03-20 00:11 UTC
### Problem description

Steps to reproduce:
1. Set colorscheme to something that is not **onedarker**.
e.g.  `lvim.colorscheme = "pablo"`
2. Run PackerSync
3. Restart lunarvim

You will see that the colorscheme will be the default.  However, if you use **onedarker** colorscheme it works.

It is due to #2359.

This is because in that change `vim.cmd("colorscheme " .. lvim.colorscheme)` was removed in plugin-loader.lua.

It works for the onedarker colorscheme, because its init.lua has `vim.cmd [[colorscheme onedarker]]`

I am not sure what the fix is, as there were probably good reasons for #2359.  As a workaround I can run the colorscheme command manually, or just add the `vim.cmd` to my config file, but that seems like and undesirable requirement.

### LunarVim version

Latest Rolling

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Linux

### Relevant log output

```shell
N/A
```

**Comment by angryheng** [comment] 2022-03-20 02:35
same issue

**Comment by Israr** [comment] 2022-03-20 03:49
I also just updated and hit the same issue.

**Comment by abzcoding** [comment] 2022-03-20 10:34
@kylo252 maybe we need to update readme or add back the `colorscheme` thingy

**Comment by abzcoding** [comment] 2022-03-20 10:34
duplicate of #2364

**Closed by abzcoding** 2022-03-20 10:34 UTC
Labels: bug

**Comment by sa-mendez** [comment] 2022-03-20 19:46
I see that its fixed.  Thank you
