### ISSUE TITLE
Tailwindcss LSP not attaching to corresponding filetypes

### ISSUE THREAD

**Issue by rfn900** [LunarVim/LunarVim#2384] opened 2022-03-23 21:48 UTC
### Problem description

# Issues with Tailwindcss LSP

Running lunarvim (v1.1.2) on Arch Linux.  I can´t get the Tailwindcss client to attach to any of the corresponding filetypes, like `.html`, `.js`, `.jsx`. etc. All the other LSPs are working fine. 

I can see that the server is listed as installed but there is no way to actually get it to work.

Something I am missing?

### LunarVim version

1.1.2

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

Arch Linux (Arcolinux)

### Affected language servers

tailwindcss

### Steps to reproduce

1. Load a `.js` or `.html` file
2. Wait for the automatic installation to kick in
3. See tailwindcss attached to buffer when you run `:LspInfo`

### Actual behavior

It never installs and when I install manually, it never attaches to the buffer no matter which filetype I am currently working on.

### log and support info

```shell
:LspInstallInfo - Shows that tailwindcss is installed
:LspInfo - Doesn´t show it attached to buffer
```

**Comment by abzcoding** [comment] 2022-03-24 07:56
we've ignored `tailwindcss`
https://github.com/LunarVim/LunarVim/blob/3c152cb1cf768e3111543d3070e6efd6cfacbb1c/lua/lvim/lsp/config.lua#L97-L99

so you have to set it up yourself, according to	https://www.lunarvim.org/languages/#server-setup

**Comment by kylo252** [comment] 2022-03-25 14:24
Duplicate of https://github.com/LunarVim/LunarVim/issues/2299

**Closed by kylo252** 2022-03-25 14:24 UTC
Labels: bug
