### ISSUE TITLE
Out of the box lunarvim installation. Getting EACCES: permission denied when using null-ls

### ISSUE THREAD

**Issue by maelmmm** [LunarVim/LunarVim#3148] opened 2022-10-04 19:57 UTC
### Problem description

I am trying to get a formatter work for python, by uncommenting the lines 129-142 in the config.lua file. But I get an error similar to the one described in Issue https://github.com/LunarVim/LunarVim/issues/3086 . Unfortunately I wasn't able to resolve it. 

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Affected language servers

null-ls

### Actual behavior

formatting not working. EACCES denied for null-ls

### support info

Running: :LspInfo 

Client: null-ls (id: 2, pid: 5001, buffer: [7])
 filetype: python
 autostart: false 
 root directory: /Users/mm/Code_Projects
 cmd: nvim

### Screenshots

<img width="507" alt="Screenshot 2022-10-04 at 21 56 52" src="https://user-images.githubusercontent.com/80274965/193913557-1e7e7cb5-68d2-4f40-bb07-b2ce585b5376.png">

**Comment by ChristianChiarulli** [comment] 2022-10-04 20:40
how did you install node?

**Comment by rebuilt** [comment] 2022-10-04 20:51
Read this: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

It's linked in the documentation here
https://www.lunarvim.org/01-installing.html#prerequisites

Another common problem is that some formatters/language servers depend on newer versions of node.  Make sure you have a newish version of node on your machine.

**Comment by maelmmm** [comment] 2022-10-05 08:32
I installed node via nvm, which is what they advice to avoid permission mistakes. but unfortunately the problem persist. I also have the newest version of node.

**Comment by ChristianChiarulli** [comment] 2022-10-05 15:39
what is the output of `which node`?

**Comment by maelmmm** [comment] 2022-10-05 15:41
`/Users/mm/.nvm/versions/node/v18.10.0/bin/Node`

**Comment by ChristianChiarulli** [comment] 2022-10-05 15:45
weird that you're on Neovim 0.8 and using the master branch for lunarvim. Might not be an issue but I'm not sure what issues that could cause.

**Comment by kobzar** [comment] 2022-10-11 09:46
Try to update npm
npm install -g npm@latest

**Comment by maelmmm** [comment] 2022-10-11 11:48
I updated npm. Unfortunately there is still an error with [null-ls] see below 
`[null-ls] failed to run generator: .../null-ls.nvim/null-ls/loop.lua:157: fail`

**Comment by kobzar** [comment] 2022-10-11 12:51
attach your config please

show out of 
npm install jslint  (runned from user - not sudo)
Try to uninstal/install Lvim

**Comment by vunhatchuong123** [comment] 2022-10-24 06:42
I encounter this problem as well for pyright.
```bash
Spawning language server with cmd: `pyright-langserver` failed with error message: EACCES: permission denied
Error executing Lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1602: client_id: expected number, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1602: in function 'buf_attach_client'
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:128: in function 'launch'
        ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:81: in function <...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:69>
```
C++ works fine

**Comment by kobzar** [comment] 2022-10-24 09:34
OK. The issue is resolved

**Closed by kobzar** 2022-10-24 09:34 UTC
Labels: bug

**Comment by w-r-z-k** [comment] 2022-12-09 00:41
Same issue.  Installing on a Mac.  I run the LunarVim installer.  It says:

```
[WARN]: skipping installing optional nodejs dependencies due to insufficient permissions.
check how to solve it: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
```

I read that article, which tells me to do:

`npm install -g npm`

which I do.  Then I re-run the LunarVim installer and get the same thing.

I was hoping this would be easy to install.

**Comment by rebuilt** [comment] 2022-12-09 01:48
> npm install -g npm

Keep reading that article.   The command listed above installs the latest version but it doesn't install a version manager like `nvm`.

```
We strongly recommend using a Node version manager like [nvm](https://github.com/nvm-sh/nvm) to install Node.js and npm. We do not recommend using a Node installer, since the Node installation process installs npm in a directory with local permissions and can cause permissions errors when you run npm packages globally.
```

The section you want is here: https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#osx-or-linux-node-version-managers

Or, you could follow the instructions here to manually change the default directory: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by w-r-z-k** [comment] 2022-12-09 03:34
Thanks.  I guess I'll have to learn about node and npm installations.  

Also, I'll need to solve the rust installation problems:

```
Installing missing Rust dependency with cargo
    Updating crates.io index
warning: spurious network error (2 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
warning: spurious network error (1 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
^C     Fetch [======>                  ]  30.64%, 16.35MiB/s
```

There's an article here that gives a hint: [[Cargo fails with "spurious network error: The operation timed out" on Windows 10 when using a local user](https://stackoverflow.com/questions/45722823/cargo-fails-with-spurious-network-error-the-operation-timed-out-on-windows-10)]

But it leaves me wondering why I'm spending so much time figuring out node, rust, and python when I want to install LunarVim to use a completely different language.
