### ISSUE TITLE
vimtex does not work

### ISSUE THREAD

**Issue by xyegithub** [LunarVim/LunarVim#3723] opened 2023-01-13 11:54 UTC
### Problem description

When `lervag/vimtex` is added as a plugin, it is not loaded, i.e., the command like ":VimtexClean" defined in `vimtex` can not be used. However, when use the 'rolling' branch of lunarvim, `vimtex` can be used correctly.

### LunarVim version

master-f4ec3fc

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-661+ga37c686d2

### Operating system/version

Ubuntu 22.04

### Steps to reproduce

The configure file is 
```lua
lvim.plugins = {
  { "lervag/vimtex",
    config = function()
      vim.g.vimtex_view_general_viewer = 'okular'
      vim.g.vimtex_view_general_options = [[--unique file:@pdf\#src:@line@tex]]
      vim.g.vimtex_quickfix_enabled = 1
      vim.g.vimtex_syntax_enabled = 1
      vim.g.vimtex_quickfix_mode = 0
    end,
    ft = 'tex'
  },
}
```
The command such as `:VimtexClean` can not be used after `Sync` the plugins. Only the command `:VimtexInverseSearch` can be used. 

I notice that the command `:VimtexInverseSearch` is defined in the `plugin` folder in the root directory of `vimtex` and more command such as `:VimtexClean` defined in the `autoload` folder in the root directory of `vimtex` can not be used.  However, all the commands works well when I use the `rolling` branch of `lunarvim`.

### Screenshots

`Vimtex` is said to be loaded when i open a `tex` file.

![image](https://user-images.githubusercontent.com/46625185/212314034-17334d5d-92bc-4f0f-84a3-7b1a9c6fc72b.png)

However, only the command `VimtexInverseSearch` is loaded.

![image](https://user-images.githubusercontent.com/46625185/212314075-ff0e3552-bcef-41e9-9e41-1e3a2dd7cc70.png)

**Comment by LostNeophyte** [comment] 2023-01-13 13:25
I think the issue is in lazy.nvim, [file a bug there](https://github.com/folke/lazy.nvim/issues), I could reproduce using init.lua from <https://github.com/folke/lazy.nvim/issues/230>

**Comment by youdaniel** [comment] 2023-01-18 18:27
@LostNeophyte Vimtex works fine with that init.lua on my system. It doesn't work through LunarVim though

**Comment by afaikiac** [comment] 2023-01-19 16:58
Based on this issue LunarVim/LunarVim#1388, I solved the problem with command:
```lua
-- lvim/ftplugin/tex.lua
vim.cmd("call vimtex#init()")
```
```lua
-- lvim/config.lua
lvim.plugins = {
  {
    "lervag/vimtex",
    ft = "tex",
    lazy = false, -- already lazy loaded by virtue
  },
}
```

But like @youdaniel said, `vimtex` configured by `lazy-nvim` works fine in `neovim`. Without any hacks.

**Comment by LostNeophyte** [comment] 2023-01-19 17:06
`lazy` is false by default in lunarvim

**Comment by LostNeophyte** [comment] 2023-01-19 17:14
![image](https://user-images.githubusercontent.com/110467150/213513366-e831bde9-3663-400f-bcab-e0a7eb8bfc43.png)
this is from lazy.nvim's minimal init. 

@afaikiac can you reproduce the issue using the mininal init from the issue linked in my first comment?

**Comment by afaikiac** [comment] 2023-01-19 21:28
@LostNeophyte

Neovim with the minimal `init.lua` from the issue:
![image](https://user-images.githubusercontent.com/45965330/213564229-2877c2a7-be0c-4f87-8986-a76022994c18.png)

LunarVim with the minimal `config.lua`:
![image](https://user-images.githubusercontent.com/45965330/213565897-79d2eed6-f87f-4fa0-8d1c-18313322d12a.png)

**Comment by LostNeophyte** [comment] 2023-01-19 21:30
Idk what's wrong with setup then but i can't fix it in Lunarvim without it working in nvim first. Will try more tomorrow

**Comment by Pablorious** [comment] 2023-01-25 03:18
I have this similar issue and have tried all the remedies provided and the only thing that gets vimtex 'working' is calling `:lua=vim.cmd 'call vimtex#init()'`  from the console directly. Although even with \documentclass \begin{document} etc it still cannot find the proper main .tex file. Not sure what to do :/

**Comment by xyegithub** [comment] 2023-02-20 03:14
I added `vim.cmd("call vimtex#init()")`  in my configuration function of `vimtex`. When I open `a.tex` using `lvim a.tex`, `vimtex` is loaded correctly. However, after  opening `a.tex`, I open `b.tex` in a new buffer using `:e b.tex`, `vimtex` is not loaded for correctly for the buffer `b.tex`.

**Comment by davibarreira** [comment] 2023-04-07 13:58
Has any solution been found for your case, @xyegithub ?

**Comment by dattlab** [comment] 2023-04-09 13:59
So the solution is still just adding this `vim.cmd("call vimtex#init()")`?

With minimal init, `vimtex` works every time I open any `tex` file. In LunarVim as said above, you have to explicitly open the file like
```
$ lvim main.tex
```
and the `vimtex` will **only** work in that specific file. It will not work when you open another `tex` files in another buffer for example.

**Comment by afaikiac** [comment] 2023-04-09 15:09
>  In LunarVim as said above, you have to explicitly open the file like ...

Everything works fine for me with this configuration:

```
-- lvim/ftplugin/tex.lua
vim.cmd("call vimtex#init()")
```
```
lvim.plugins = {
	"lervag/vimtex",
}
```

**Comment by xyegithub** [comment] 2023-04-10 02:03
No. I am currently using the rolling branch of lunarvim.

**Comment by LostNeophyte** [comment] 2023-04-10 06:51
the rolling branch is deprecated, use master or 1.2

**Comment by xyegithub** [comment] 2023-04-10 07:47
OK. I often use `vimtex`. I will try 1.2 and I prefer to use the master branch when `vimtex` can be used correctly.

**Comment by davibarreira** [comment] 2023-04-10 11:42
@xyegithub , I've "fixed" it using:
```
augroup vimtex_group
  autocmd!
  autocmd FileType tex call vimtex#init()
augroup END

```
In my `.vimrc`.

**Comment by xyegithub** [comment] 2023-04-14 01:53
I add 

```lua
vim.cmd [[
  " augroup vimtex_group
  "   autocmd!
  "   autocmd FileType tex call vimtex#init()
  " augroup end
]]
```
to my configuration file. However, the following error occurs when a `tex` file is open.
 
![image](https://user-images.githubusercontent.com/46625185/231921199-a8d0e52a-c391-478d-b8ca-7e050488b7e4.png)

**Comment by dattlab** [comment] 2023-04-14 04:00
As of now, the band-aid solution is putting the command below in `.config/lvim/after/ftplugin/tex.lua`:

```lua
vim.cmd("call vimtex#init()")
```

**Comment by JxJxxJxJ** [comment] 2023-04-25 21:44
With this fix now vimtex does not distinguish between enviroments, everything seems to be text now. 
![image](https://user-images.githubusercontent.com/103049321/234411177-2fce64cf-5d7b-4993-9cf4-d5d75780e193.png)
This causes problems because I also use snippets that use these enviroments as conditions to be triggered.

**Comment by lervag** [comment] 2023-05-03 13:35
> The configure file is
> 
> ```lua
> lvim.plugins = {
>   { "lervag/vimtex",
>     config = function()
>       vim.g.vimtex_view_general_viewer = 'okular'
>       vim.g.vimtex_view_general_options = [[--unique file:@pdf\#src:@line@tex]]
>       vim.g.vimtex_quickfix_enabled = 1
>       vim.g.vimtex_syntax_enabled = 1
>       vim.g.vimtex_quickfix_mode = 0
>     end,
>     ft = 'tex'
>   },
> }
> ```

I believe this is lazy.nvim configuration. First: DON'T use lazy loading of VimTeX - remove `ft = 'tex'`! VimTeX is already lazy by use of the `ftplugin` mechanism. Also, I strongly recommend that VimTeX configuration is put in the `init` block. That way we ensure that the options are defined before VimTeX is initialized. I.e., the configuration should look more like this:

```lua
  {
    "lervag/vimtex",
    init = function()
      vim.g.vimtex_view_general_viewer = 'okular'
      vim.g.vimtex_view_general_options = [[--unique file:@pdf\#src:@line@tex]]
      vim.g.vimtex_quickfix_enabled = 1
      vim.g.vimtex_syntax_enabled = 1
      vim.g.vimtex_quickfix_mode = 0
    end,
  }
```

Also, everyone: you should _not_ need to do the manual `call vimtex#init()`. If you do, then there must be a problem with how LunarVim uses lazy.nvim. I personally use lazy.nvim with configuration more or less like the above block; it works exactly as expected.

**Comment by LostNeophyte** [comment] 2023-05-03 13:40
this issue is most likely caused by  #3941 which is caused by this part of the lazy.nvim config used by lunarvim 
```lua
require("lazy").setup(plugins, {
    performance = {
        rtp = {
            reset = false,
        },
    },
})

**Comment by LostNeophyte** [comment] 2023-05-03 13:58
> Ah, yes, I believe you are right. It should be easy to verify by inspecting the runtimepaths

with this configuration vimtex would be probably (I didn't test it yet) at the end of the rtp

> Are you planning to fix this from LunarVim's side? If not, then I think we should find a reasonable suggestion for how users can fix this - but it should also be clearly stated that the suggested configuration is not recommended except for LunarVim.

I'm not quite sure yet on whose side (lazy.nvim/lunarvim), but it should be fixed 100%, but i'm not sure who should fix it yet, I'll need to do some testing and get more familiar with the topic since I'm not sure what is the difference between packpath and rtp, correct rtp order, etc. I just found https://github.com/folke/lazy.nvim/commit/5eb2622a4e4e52bed94b5c8ae48b83ccfab0098d which is interesting, I'll do some testing, maybe even later today.

**Comment by LostNeophyte** [comment] 2023-05-04 08:40
> Great, glad to hear it. As a plugin author, I would expect a plugin manager to inject my plugin into the runtimepath in a location like this:
> 
> ```
> /home/lervag/.config/nvim
> ...
> /home/lervag/.local/plugged/vimtex
> ...
> /usr/share/nvim/runtime
> /usr/lib/nvim
> ...
> /home/lervag/.local/plugged/vimtex/after
> ...
> /home/lervag/.config/nvim/after
> ```
> 
> And indeed, this is what I observe from lazy.nvim.
> 
> This order will ensure that personal configuration (from `/home/lervag/.config/nvim`) has highest priority. Further, "external plugins" loaded with the plugin manager will be higher priority than built-in plugins (from `/usr/share/nvim` and similar).

thank you, that helped

**Closed** 2023-05-07 08:36 UTC
Labels: bug
