### ISSUE TITLE
[Bug]: Cannot Install Lvim on Macos

### ISSUE THREAD

**Issue by tejasn14** [LunarVim/LunarVim#1464] opened 2021-09-04 05:48 UTC
### Problem description

When I run the rolling install script 
>LVBRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)

I get the following error
```
--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to check lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
npm ERR! code EEXIST
npm ERR! path /opt/homebrew/bin/tree-sitter
npm ERR! EEXIST: file already exists
npm ERR! File exists: /opt/homebrew/bin/tree-sitter
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tejas/.npm/_logs/2021-09-04T05_25_44_871Z-debug.log
```

It prompts me to uninstall tree-sitter, but tree-sitter is installed as a dependency to Neovim
```
➜  lvim brew uninstall tree-sitter
Error: Refusing to uninstall /opt/homebrew/Cellar/tree-sitter/0.20.0
because it is required by neovim, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies tree-sitter
```
System:

I am using an M1 mac with Neovim installed through homebrew

**giving no on all 3 dependencies installs lunarvim without any problem**

### LunarVim version

latest rolling install

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment] 2021-09-04 13:14
we should check if the binary is already there, if it is then just move on.

**Comment by abzcoding** [comment] 2021-09-04 16:27
we are checking for the existence already
<img width="366" alt="Screen Shot 2021-09-04 at 8 56 40 PM" src="https://user-images.githubusercontent.com/10992695/132101616-eff2f9b1-43f3-401f-b5e0-30ca7fe69d35.png">

**Comment by abzcoding** [comment] 2021-09-04 16:33
i guess we can check for `tree-sitter` command as well 🤷

**Comment by Callendor** [comment] 2021-09-05 05:12
ran into this issue too - skipped ahead but still having issues getting lvim to launch from the rolling release

**Comment by abzcoding** [comment] 2021-09-05 07:35
> ran into this issue too - skipped ahead but still having issues getting lvim to launch from the rolling release.
> 
> skipped ahead and finished the rest of the installation and tried to run 'lvim' but I'm getting the following error after hitting the 'Installation is now up to date' logging.
> `-bash: lvim: command not found`

lvim binary will be in `~/.local/bin/lvim` either alias it or add it to your path

**Comment by ngki** [comment] 2021-09-06 01:12
I have the same error, also Mac M1 with NeoVim installed through Homebrew, any news?

**Comment by abzcoding** [comment] 2021-09-06 09:27
@tejasn14 @ngki can you guys test if this fixes the installation issue?
```sh
curl https://raw.githubusercontent.com/abzcoding/LunarVim/bugfix/brew-installation/utils/installer/install.sh --output install.sh
bash install.sh
```

**Comment by yudhiesh** [comment] 2021-09-09 03:19
Same issue here and this does not fix it

> @tejasn14 @ngki can you guys test if this fixes the installation issue?
> 
> ```shell
> curl https://raw.githubusercontent.com/abzcoding/LunarVim/bugfix/brew-installation/utils/installer/install.sh --output install.sh
> bash install.sh
> ```

**Comment by gonzaloserrano** [comment] 2021-09-11 08:31
@abzcoding taking a look at that code I think it uses `npm ls -g` to check whether tree-sitter is installed, but that won't work because it was not installed via npm but brew.

**Comment by alechp** [comment] 2021-09-13 17:49
> @tejasn14 @ngki can you guys test if this fixes the installation issue?
> 
> ```shell
> curl https://raw.githubusercontent.com/abzcoding/LunarVim/bugfix/brew-installation/utils/installer/install.sh --output install.sh
> bash install.sh
> ```

What I'm seeing:
<img width="1552" alt="Screen Shot 2021-09-13 at 10 41 56 AM" src="https://user-images.githubusercontent.com/3058939/133131291-01f36299-a384-4d55-b037-82c919d77395.png">


Possibly related issue:
https://github.com/wbthomason/packer.nvim/issues/502#issuecomment-896055778


---

Since initial issue I filed a month or so ago, I re-tested:
- Stable, Rolling a couple times each with slight changes 
> Also, tried the rolling update after this PR was merged: https://github.com/LunarVim/LunarVim/pull/1540

Additional context:
- Tested this curl command install after full uninstall
- Tried stable and rolling with and without packer installed locally via brew
- Went through full uninstall between each iteration (including packer plugins)
- Confirmed that PackerInstall/PackerSync commands crashes
- Setup lvim alias to get it working; you can tell base of LunarVim loaded, but that's it (couldn't even open up tree)

Observations:
- Whatever the problem, macOS issue seems to be packer related
- As pointed out above, the early fail on the npm dep is easily resolved by uninstalling tree-sitter with brew (did this so I can confirm that solves temporarily)
- Even when I get this installed without errors (like screenshot above) still can't run :PackerInstall or :PackerSync without crashing terminal

**Comment by zapman449** [comment] 2021-09-15 21:47
For me, experiencing the same macos/brew/tree-sitter problem, this does not fix it, but does produce a new error:

```
--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install lunarvim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with npm..
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "tree-sitter-cli,tree-sitter": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jprice/.npm/_logs/2021-09-15T21_45_41_612Z-debug.log
```

That log file has this content towards the end:

```
28 timing idealTree:init Completed in 5ms
29 timing idealTree Completed in 6ms
30 timing command:install Completed in 40ms
31 verbose stack Error: Invalid tag name "tree-sitter-cli,tree-sitter": Tags may not have any characters that encodeURIComponent encodes.
31 verbose stack     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:89:15)
31 verbose stack     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:343:13)
31 verbose stack     at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:80:12)
31 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:48:10)
31 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:465:50
31 verbose stack     at Array.map (<anonymous>)
31 verbose stack     at Arborist.[add] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:462:28)
31 verbose stack     at Arborist.[applyUserRequestsToNode] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:437:23)
31 verbose stack     at Arborist.[applyUserRequests] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:386:43)
31 verbose stack     at Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:205:37)
32 verbose cwd /private/tmp
33 verbose Darwin 20.6.0
34 verbose argv "/usr/local/Cellar/node/16.8.0/bin/node" "/usr/local/bin/npm" "install" "-g" "tree-sitter-cli,tree-sitter"
35 verbose node v16.8.0
36 verbose npm  v7.21.0
37 error code EINVALIDTAGNAME
38 error Invalid tag name "tree-sitter-cli,tree-sitter": Tags may not have any characters that encodeURIComponent encodes.
39 verbose exit 1
```

**Comment by zapman449** [comment] 2021-09-15 21:53
If I change install.sh to say:

```
declare -a __npm_deps=(
  "neovim"
  "tree-sitter"
)
```
(remove tree-splitter-cli) the process gets a lot further, but blows up with a weird npm error:

```
Installing node modules with npm..
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/tree-sitter
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
npm ERR!   LIBTOOL-STATIC Release/tree_sitter.a
npm ERR!   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.8.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! (node:48123) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/tree-sitter/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jprice/Library/Caches/node-gyp/16.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jprice/Library/Caches/node-gyp/16.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jprice/Library/Caches/node-gyp/16.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/tree-sitter',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/binding.cc:1:
npm ERR! In file included from /Users/jprice/Library/Caches/node-gyp/16.8.0/include/node/node.h:63:
npm ERR! In file included from /Users/jprice/Library/Caches/node-gyp/16.8.0/include/node/v8.h:30:
npm ERR! /Users/jprice/Library/Caches/node-gyp/16.8.0/include/node/v8-internal.h:488:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/tree_sitter_runtime_binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/tree-sitter
npm ERR! gyp ERR! node -v v16.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jprice/.npm/_logs/2021-09-15T21_52_14_276Z-debug.log
```

**Comment by rafaelderolez** [comment] 2021-09-21 12:50
Is there anything else us macOS users can provide? Would love to give Lunarvim a shot!

**Comment by abzcoding** [comment] 2021-09-21 12:52
we are planning to create a brew for it, in the meantime you can manually install the requirements and press no to those

**Comment by Callendor** [comment] 2021-10-03 01:59
> we are planning to create a brew for it, in the meantime you can manually install the requirements and press no to those

looking forward to it!!!!

**Comment by zapman449** [comment] 2021-10-07 17:49
Where are the requirements documented?

**Comment by alechp** [comment] 2021-11-03 20:51
> Where are the requirements documented?

@zapman449 Did you get the install working on mac?

**Closed** 2021-12-21 09:02 UTC
Labels: bug, packaging

**Comment by rafo** [comment] 2022-09-03 15:18
Just run into this problem with macOS + M1 + Homebrew. Since it still exists, it would be great to hint this in the documentation.

**Comment by rafo** [comment] 2022-09-03 15:54
> > Where are the requirements documented?
> 
> https://www.lunarvim.org/01-installing.html#prerequisites

Where are the **NodeJS dependencies** documented?
