### ISSUE TITLE
icons from diagnostics cause weird indentations

### ISSUE THREAD

**Issue by ccbiozhaw** [LunarVim/LunarVim#4202] opened 2023-05-25 15:33 UTC
### Problem description

in particular the DiagnosticsHint icon causes a small indentation (looks like 1 space), that causes a lot of visual stress, and there appear visual distortions because of the whole movements (for example some letters appear duplicate when you move back and forth that one space.. a "word next" might appear as "worddnext".

![image](https://github.com/LunarVim/LunarVim/assets/80820813/a70f3bc2-454c-4cad-a674-8ec4c7d32184)

once you move the cursor over it, it returns back to normal (but gets back indented when you move out and back into view).

![image](https://github.com/LunarVim/LunarVim/assets/80820813/66e3fc82-59cc-48c0-af42-08901d97b169)

for me this happens on the default lunarvim settings on my work pc and my personal mac.

i noticed that this is most likely caused by the icons, and when i disable them everything works fine:

![image](https://github.com/LunarVim/LunarVim/assets/80820813/2adda2d9-88d8-4123-851a-6c217973b918)

### LunarVim version

LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)

### Neovim version (>= 0.9.0)

0.9

### Operating system/version

macos and linux

### Affected language servers

all

### Actual behavior

weird indentations

### Expected behavior

no indentation

### support info

lsp info shows the attached servers

**Comment by LostNeophyte** [comment] 2023-05-25 17:26
you chose a wrong issue template, what's your terminal?

duplicate of https://github.com/LunarVim/LunarVim/issues/4152#issuecomment-1540917862, update your font/terminal

**Closed by LostNeophyte** 2023-05-25 17:26 UTC
Labels: duplicate

**Comment by ccbiozhaw** [comment] 2023-05-25 18:16
wezterm and windows terminal. its the same on both

**Comment by ccbiozhaw** [comment] 2023-05-31 09:03
okay this seems to be caused by tmux + nvim. It happened to me on all terminals and even when disabling all fonts. These indentations occured even when just the default emblem (you get when its not available) was displayed. This did not happen with my usual nvim configuration either, only with lvim.

It might not be an issue of lvim directly, however one of the plugins you have, or a version of it does. maybe its the webdev icons, but i dont know how to update it.

what does work for now is to just overwrite the plugins in config.lua:


```
 local signs = {
    { name = "DiagnosticSignError", text = "" },
    { name = "DiagnosticSignWarn", text = "" },
    { name = "DiagnosticSignHint", text = "" },
    { name = "DiagnosticSignInfo", text = "" },
  }

for _, sign in ipairs(signs) do
  vim.fn.sign_define(sign.name, { texthl = sign.name, text = sign.text, numhl = "" })
end

vim.diagnostic.config({signs = signs})
```

**Comment by LostNeophyte** [comment] 2023-05-31 09:38
Report the bug to tmux in that case

**Comment by ccbiozhaw** [comment] 2023-05-31 10:38
it might be a bug with tmux, nevertheless this is also an issue of lunarvim, and I am not the only one that has it. 

This is caused by some of the icons. 
It wasnt an issue in the past, but now is. 
It happens with the folder emblem too for example. In the past lvim had the bottom emblem (out of those 2 images), and switched it to the upper one (its slightly smaller i think).

![image](https://github.com/LunarVim/LunarVim/assets/80820813/ffab874a-e83f-4da8-a61c-84b1afc53b1a)

I want to note that this causes issues in the terminal as well - completely removed from nvim.

![image](https://github.com/LunarVim/LunarVim/assets/80820813/784c8581-035d-4650-9a3e-54d81ae5fe0c)

just hitting space adds an other symbol lol...

![image](https://github.com/LunarVim/LunarVim/assets/80820813/5337d323-9415-4574-ae53-2144f2781853)

it might have something to do with spacing?

either way, this is an issue with some of the emblems. they are easy to spot because they cause distortions:

you will see that the line highlight changes after the icon:
![image](https://github.com/LunarVim/LunarVim/assets/80820813/57154c65-0b9a-4d20-afe5-49defd06e31a)

sometimes it adds random characters, like periods:
![image](https://github.com/LunarVim/LunarVim/assets/80820813/b123708e-4590-4732-b00e-46bd55dfc0e5)


all of the icons that cause issues were added in commit:

https://github.com/LunarVim/LunarVim/commit/44c1a3d738b54682e857e5e62ef358f1f793d086

i set them to the old ones and everything is fine.

**Comment by LostNeophyte** [comment] 2023-05-31 10:53
Nerd fonts updated their icons and some of them take more bytes to store, some programs render them incorrectly, nothing we can do about it

**Comment by ccbiozhaw** [comment] 2023-05-31 11:01
yea you can, just use the ones that do not cause issues. Its only a handful of the new icons that behave like that, and their replacements look exactly the same. its causing a headache for no reason

**Comment by LostNeophyte** [comment] 2023-05-31 13:32
> yea you can, just use the ones that do not cause issues. Its only a handful of the new icons that behave like that, and their replacements look exactly the same. its causing a headache for no reason

there are no other icons that look the same, they are deprecated
