### ISSUE TITLE
Freeze plugin state for stable releases

### ISSUE THREAD

**Issue by ChristianChiarulli** [LunarVim/LunarVim#576] opened 2021-07-01 15:23 UTC
For stable releases we should create a branch, freeze required plugins to a specific commit, then create a stable release.

**Comment by rebuilt** [comment] 2021-07-01 15:31
This means requiring a specific version of neovim as well.

**Comment by ChristianChiarulli** [comment] 2021-07-01 15:47
@rebuilt good point

**Comment by ChristianChiarulli** [comment] 2021-07-07 06:40
there will forever be bugs if we don't pin these. I don't think neovim version will be that big of a deal.

**Comment by ChristianChiarulli** [comment] 2021-07-07 06:42
I have an example in for nvimtree now.

**Comment by abzcoding** [comment] 2021-08-08 21:41
duplicate of #1265

**Closed by abzcoding** 2021-08-08 21:41 UTC
Labels: enhancement, help wanted
