### ISSUE TITLE
Lunarvim welcome screen loading partially on Window 11

### ISSUE THREAD

**Issue by FBI-b0t** [LunarVim/LunarVim#3793] opened 2023-01-29 19:30 UTC
### Problem description

I installed LunarVim by following the installation procedure [from the official website](https://www.lunarvim.org/docs/installation)

All the prerequisites were installed and I followed the instruction to install the stable release on my system (Windows 11).
And by typing "lvim" in PowerShell LunarVim's welcome screen is partially loaded or something...

Can you help me fix it?

### LunarVim version

release-1.2/neovim-0.8-8f4a7bde

### Neovim version (>= 0.8.0)

NVIM v0.8.2

### Operating system/version

Windows 11

### Screenshots

This is what happened:

Image:
<img width="960" alt="Screenshot_20230129_014201" src="https://user-images.githubusercontent.com/95200294/215349727-84eea5e0-4a2d-4754-991f-3a30257347ed.png">

Video:
https://user-images.githubusercontent.com/95200294/215349730-be1b57e2-84bf-40e7-867e-2440c6435fcd.mp4

**Comment by LostNeophyte** [comment] 2023-01-30 09:34
duplicate of https://github.com/LunarVim/LunarVim/issues/3279, it's fixed on master

**Closed by LostNeophyte** 2023-01-30 09:34 UTC
Labels: bug
