### ISSUE TITLE
[Feature]: Allow remapping of lsp keybindings

### ISSUE THREAD

**Issue by marcomayer** [LunarVim/LunarVim#1601] opened 2021-09-22 10:08 UTC
### Feature motivation

Currently, it's not possible, or at least I couldn't figure out how to remap the lsp related keybindings in the user config. These are set in lsp/init.lua add_lsp_buffer_keybindings() and always called on M.common_on_attach() so they'll overwrite any user settings set in the mappins like:
`lvim.keys.normal_mode["gr"] = [[<Cmd>lua require('telescope.builtin').lsp_references({path_display={'shorten'}})<CR>]]`

### Describe the expected solution

Allow this to be part of the user config, the quickest but probably not best solution would be to have an option that is checked on whether to call add_lsp_buffer_keybindings() or not. Ideally, it would get integrated into the mappings.

**Comment by abzcoding** [comment] 2021-09-23 07:52
duplicate of #1494

**Closed by abzcoding** 2021-09-23 07:52 UTC
Labels: enhancement
