### ISSUE TITLE
File path and change status interfere with editor

### ISSUE THREAD

**Issue by Aym3nJ** [LunarVim/LunarVim#3514] opened 2022-11-22 23:56 UTC
### Problem description

I get this with what ever type of file with my brand new installation of LunarVim
the File path and change status interfere get on the way of the line i'm writing on 

![image](https://user-images.githubusercontent.com/48295969/203443541-6e8a9563-edff-4aed-adcd-c89e5bd3b05d.png)

i have default installation(all options i did "Yes"  ) with  minimal modification of the config file adding the following:
`vim.opt.relativenumber = true -- set relative numbered lines`

### LunarVim version

Realease-1.2

### Neovim version (>= 0.8.0)

0.8.0

### Operating system/version

Fedora Linux 37 (Workstation Edition)

### support info

```
Language client log: /home/aymen/.local/state/nvim/lsp.log
 Detected filetype:   rust
 
 1 client(s) attached to this buffer: 
 
 Client: rust_analyzer (id: 1, pid: nil, bufnr: [7])
 	filetypes:       rust
 	autostart:       true
 	root directory:  /home/aymen/Dev/Rust/bat
 	cmd:             rust-analyzer
 
 Configured servers list: rust_analyzer
```

```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                swayconfig
* bufnr:                   7
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, glint, golangci_lint_ls, gradle_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, reason_ls, rome, ruby_ls, solang, solc, sorbet, sourcery, sqlls, sqls, stylelint_lsp, svlangserver, tflint, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

**Comment by Aym3nJ** [comment] 2022-11-23 02:38
After more investigation i realize that this happens on Alacritty but not on St

**Comment by LostNeophyte** [comment] 2022-11-23 05:47
Duplicate of https://github.com/LunarVim/LunarVim/issues/3481, please check if the issue has been already opened by someone else before opening another one. There were like 5 issues about this thing. You can see the mentioned issue for a temporary fix

**Closed by LostNeophyte** 2022-11-23 05:47 UTC
Labels: bug
