### ISSUE TITLE
Problem with update/install lunarvim

### ISSUE THREAD

**Issue by RomjanHossain** [LunarVim/LunarVim#2471] opened 2022-04-15 02:33 UTC
### Problem description

After updating Lunarvim This problem occurred! 

```
	.../romjan/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
	...mjan/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:32: in function 'init'
	...romjan/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:104: in function 'init'
	/home/romjan/.local/share/lunarvim/lvim/init.lua:8: in main chunkError detected while processing command line:
```

then i tried to reinstall the luarvim and got this error again!

I'm a big fan of this project and hope to see this issue solved soon.

### LunarVim version

don't know

### Neovim version (>= 0.6.1)

NVIM v0.6.1

### Operating system/version

Manjaro 

### Relevant log output

```shell
> bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

      88\                                                   88\
      88 |                                                  \__|
      88 |88\   88\ 888888$\   888888\   888888\ 88\    88\ 88\ 888888\8888\
      88 |88 |  88 |88  __88\  \____88\ 88  __88\\88\  88  |88 |88  _88  _88\
      88 |88 |  88 |88 |  88 | 888888$ |88 |  \__|\88\88  / 88 |88 / 88 / 88 |
      88 |88 |  88 |88 |  88 |88  __88 |88 |       \88$  /  88 |88 | 88 | 88 |
      88 |\888888  |88 |  88 |\888888$ |88 |        \$  /   88 |88 | 88 | 88 |
      \__| \______/ \__|  \__| \_______|\__|         \_/    \__|\__| \__| \__|

--------------------------------------------------------------------------------
Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
Installing node modules with yarn..
yarn global v1.22.17
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "neovim@4.10.1" with binaries:
      - neovim-node-host
success Installed "tree-sitter-cli@0.20.6" with binaries:
      - tree-sitter
Done in 2.49s.
All NodeJS dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Python dependencies?
[y]es or [n]o (default: no) : y
Verifying that pip is available..
Installing with pip..
Requirement already satisfied: pynvim in ./.local/lib/python3.10/site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in /usr/lib/python3.10/site-packages (from pynvim) (1.0.3)
Requirement already satisfied: greenlet in ./.local/lib/python3.10/site-packages (from pynvim) (1.1.2)
All Python dependencies are successfully installed
--------------------------------------------------------------------------------
Would you like to install LunarVim's Rust dependencies?
[y]es or [n]o (default: no) : n
--------------------------------------------------------------------------------
Backing up old /home/romjan/.config/lvim to /home/romjan/.config/lvim.old

Number of files: 3 (reg: 2, dir: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 2
Total file size: 5.85K bytes
Total transferred file size: 5.85K bytes
Literal data: 5.85K bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.002 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 6.04K
Total bytes received: 57

sent 6.04K bytes  received 57 bytes  12.20K bytes/sec
total size is 5.85K  speedup is 0.96
--------------------------------------------------------------------------------
Backup operation complete
--------------------------------------------------------------------------------
Removing old installation files
--------------------------------------------------------------------------------
Cloning LunarVim configuration
Cloning into '/home/romjan/.local/share/lunarvim/lvim'...
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 150 (delta 5), reused 56 (delta 3), pack-reused 0
Receiving objects: 100% (150/150), 115.00 KiB | 1.09 MiB/s, done.
Resolving deltas: 100% (5/5), done.
--------------------------------------------------------------------------------
Removing old startup cache file
--------------------------------------------------------------------------------
Installing LunarVim shim
make: Entering directory '/home/romjan/.local/share/lunarvim/lvim'
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /home/romjan/.local/bin/lvim
make: Leaving directory '/home/romjan/.local/share/lunarvim/lvim'
Preparing Packer setup
Error detected while processing /home/romjan/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: .../romjan/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: attempt to index field 'window' (a nil value)
stack traceback:
	.../romjan/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
	...mjan/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:32: in function 'init'
	...romjan/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:104: in function 'init'
	/home/romjan/.local/share/lunarvim/lvim/init.lua:8: in main chunkError detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
```

### Screenshots

![Screenshot_20220415_080311](https://user-images.githubusercontent.com/47692261/163507920-be5f5dab-761e-4424-8e21-263e51ad6849.png)
![Screenshot_20220415_082438](https://user-images.githubusercontent.com/47692261/163508034-773bf1bf-9368-4d5a-b36b-f2fcb9eda059.png)

**Comment by BreezyMain** [comment] 2022-04-15 03:16
i met the same problem...

**Comment by opxop** [comment] 2022-04-15 03:43
I just wanna get an update regarding this issue..

**Comment by GuangDai** [comment] 2022-04-15 04:19
same...

**Comment by cpea2506** [comment] 2022-04-15 04:25
Backup your config and remove completely `Lunarvim` from your machine then try to install again.

**Comment by JCallicoat** [comment] 2022-04-15 04:43
Dupe of #2466. This was fixed earlier by pulling in a newer nvim-cmp commit, try the commands listed here https://github.com/LunarVim/LunarVim/issues/2466#issuecomment-1099732764

**Comment by MRVAX** [comment] 2022-04-15 05:32
SAME!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MRVAX** [comment] 2022-04-15 05:37
FIXED BY REINSTALL LUNARVIM!!
UNINSTALL COMMAND: bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/uninstall.sh)
THEN RUN INSTALL COMMAND PROBABALY CAN FIX IT :D

**Comment by JCallicoat** [comment] 2022-04-15 05:47
You shouldn't need to uninstall / reinstall you just need to manually update the nvim-cmp module with the commands from https://github.com/LunarVim/LunarVim/issues/2466#issuecomment-1099732764

> it should be fixed now, make sure this command
> 
> ```shell
> git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp rev-parse HEAD
> ```
> 
> outputs `b5433f901ebffc9e01b82ae13da9a92d49569205` if it doesn't then force it using
> 
> ```shell
> git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp pull
> ```

**Comment by opxop** [comment] 2022-04-15 05:59
> You shouldn't need to uninstall / reinstall you just need to manually update the nvim-cmp module with the commands from [#2466 (comment)](https://github.com/LunarVim/LunarVim/issues/2466#issuecomment-1099732764)
> 
> > it should be fixed now, make sure this command
> > ```shell
> > git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp rev-parse HEAD
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > outputs `b5433f901ebffc9e01b82ae13da9a92d49569205` if it doesn't then force it using
> > ```shell
> > git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp pull
> > ```

thanks, solved!

**Closed** 2022-04-15 08:45 UTC
Labels: bug
